### ISSUE TITLE
[Question] Creating a unique set of URLs by gathering all of them from a domain

### ISSUE THREAD

**Issue by joe733** [scrapy-plugins/scrapy-playwright#107]
Hi, I'm creating a link crawler. You can find the code here: [joe733/link_finder](https://github.com/joe733/link_finder). I'm using `scrapy-playwright` to get all the URLs from any JS rendered webpage. Here are some gists of my setup:

[**`settings.py`**](https://github.com/joe733/link_finder/blob/69f147714c32ab178fe18a8a2dca6e9c64ba0eb1/scraper_js/goosebumps/settings.py#L102-L115)

```python
...
# Twisted
TWISTED_REACTOR = 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'

### Playwright ###
DOWNLOAD_HANDLERS = {
    'http': 'scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler',
    'https': 'scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler',
}
# pylint: disable = unnecessary-lambda-assignment
# PLAYWRIGHT_ABORT_REQUEST = (lambda req: req.resource_type == 'image')
PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE = (
    lambda req: req.resource_type not in ('image', 'script')
)
# pylint: enable = unnecessary-lambda-assignment
```

[**`parse_item`**](https://github.com/joe733/link_finder/blob/69f147714c32ab178fe18a8a2dca6e9c64ba0eb1/scraper_js/goosebumps/spiders/larvae.py#L114-L120)

```python
...
                    yield response.follow(
                        url=link.url,
                        headers=self.headers,
                        callback=self.parse_item,
                        dont_filter=True,
                        meta={'playwright': True}
                    )
```

But the URL dump does not contain links from gathered from playwright requests...

<details>
<summary>Playwright Scrapy summary</summary>

```dict
{
'downloader/exception_count': 2,
 'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 2,
 'downloader/request_bytes': 10532,
 'downloader/request_count': 36,
 'downloader/request_method_count/GET': 36,
 'downloader/response_bytes': 1637924,
 'downloader/response_count': 36,
 'downloader/response_status_count/200': 36,
 'elapsed_time_seconds': 74.68268,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 7, 13, 11, 10, 34, 966797),
 'httpcompression/response_bytes': 49,
 'httpcompression/response_count': 1,
 'item_scraped_count': 36,
 'log_count/DEBUG': 2043,
 'log_count/INFO': 15,
 'memusage/max': 101490688,
 'memusage/startup': 60338176,
 'playwright/context_count': 1,
 'playwright/context_count/max_concurrent': 1,
 'playwright/context_count/non-persistent': 1,
 'playwright/page_count': 35,
 'playwright/page_count/closed': 35,
 'playwright/page_count/max_concurrent': 8,
 'playwright/request_count': 966,
 'playwright/request_count/method/GET': 930,
 'playwright/request_count/method/POST': 36,
 'playwright/request_count/navigation': 46,
 'playwright/request_count/resource_type/document': 46,
 'playwright/request_count/resource_type/font': 100,
 'playwright/request_count/resource_type/image': 236,
 'playwright/request_count/resource_type/script': 396,
 'playwright/request_count/resource_type/stylesheet': 152,
 'playwright/request_count/resource_type/xhr': 36,
 'playwright/response_count': 965,
 'playwright/response_count/method/GET': 929,
 'playwright/response_count/method/POST': 36,
 'playwright/response_count/resource_type/document': 46,
 'playwright/response_count/resource_type/font': 100,
 'playwright/response_count/resource_type/image': 235,
 'playwright/response_count/resource_type/script': 396,
 'playwright/response_count/resource_type/stylesheet': 152,
 'playwright/response_count/resource_type/xhr': 36,
 'request_depth_max': 3,
 'response_received_count': 36,
 'robotstxt/forbidden': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 37,
 'scheduler/dequeued/memory': 37,
 'scheduler/enqueued': 37,
 'scheduler/enqueued/memory': 37,
 'start_time': datetime.datetime(2022, 7, 13, 11, 9, 20, 284117)
}
2022-07-13 16:40:34 [scrapy.core.engine] INFO: Spider closed (finished)
2022-07-13 16:40:34 [scrapy-playwright] INFO: Closing download handler
2022-07-13 16:40:34 [scrapy-playwright] INFO: Closing download handler
2022-07-13 16:40:35 [scrapy-playwright] DEBUG: Browser context closed: 'default' (persistent=False)
2022-07-13 16:40:35 [scrapy-playwright] INFO: Closing browser
```

</details>

**Issues**

- See  `'downloader/request_method_count/GET': 36`. Those 36 URLs gets written to the file, but not some links from `'playwright/request_count/method/GET': 930`. why not?

- Additionally, playwright does not seem to honor `allowed_domains`. It sends a requests to all domains scraped from a page, why?

**Comment by elacuesta** [comment]
* `playwright/request_count/method/GET` is the total amount of requests made by Playwright, including those to get additional resources (non-navigation) such as images, scripts, stylesheets, etc. These are not processed by Scrapy callbacks (which get the final result with the page rendering), but it's possible to process them by [attaching handlers to the `request` page event](https://github.com/scrapy-plugins/scrapy-playwright#handling-page-events).
* `allowed_domains` works at the Spider Middleware level (`OffsiteMiddleware`), meaning (navigation) requests which are not valid do not even reach the downloader. This works well for vanilla Scrapy, not so much with scrapy-playwright because often additional resources are hosted in different domains. We can't just use the same list of allowed domains, perhaps an alternative could be to introduce a new setting (`PLAYWRIGHT_ALLOWED_DOMAINS` or similar) to restrict this separately.

**Comment by joe733** [comment]
So I added a custom downloader middleware, but playwright still seem to ignore it.

```python
# milldewares.py
class OffsiteDownloaderMiddleware(OffsiteSpiderMiddleware):
    """OffsiteDownloaderMiddleware"""

    def process_request(self, request: Request, spider: Spider) -> None:
        """Quick-and-dirty downloader middleware to workaround"""
        if not list(self.process_spider_output(None, [request], spider)):
            raise IgnoreRequest

```

```python
# settings.py
...
DOWNLOADER_MIDDLEWARES = {
    'scraper_js.goosebumps.middlewares.OffsiteDownloaderMiddleware': 543,
}
...
PLAYWRIGHT_ABORT_REQUEST = (
    lambda req: req.resource_type in ('image', 'script', 'stylesheet', 'media')
)
```

In `scrapy-playwright` README.md, I did not find `PLAYWRIGHT_ALLOWED_DOMAINS` setting, is there a way to add a custom setting?

> The current goal is to restrain playwright from sending any HTTP request to URLs that lie outside the given domain (even block requests to subdomains).

**Comment by elacuesta** [comment]
> So I added a custom downloader middleware, but playwright still seem to ignore it.

I don't fully understand what you're trying to achieve. Which requests/domains would you like to get allowed and/or filtered out?

What I meant is that [non-navigation requests](https://playwright.dev/python/docs/api/class-request#request-is-navigation-request) (requests to get additional resources, not scheduled by the spider) do not follow `allowed_domains`, i.e. if a page needs to get something (image, stylesheet, etc) from `domain.org` it will get it regardless of whether `domain.org` is in the spider's `allowed_domains`. Moreover, non-navigation requests are not processed by Scrapy, they are internal to Playwright (this is probably why your middleware does not do what you expect). One way to filter them could be by using the `PLAYWRIGHT_ABORT_REQUEST` setting, for instance:
```python
from urllib.parse import urlparse

allowed_domains = [...]

PLAYWRIGHT_ABORT_REQUEST = (
    lambda req: urlparse(req.url).netloc not in allowed_domains
)
```

**Comment by joe733** [comment]
Hi, I understand now. But if I block non-navigational requests, the page might break or load impartially, which is not desired when scraping the same. I also realize that `allowed_domains` crawls over all  "subdomains" (but not the ones on the same level).

The setting `PLAYWRIGHT_ABORT_REQUEST` leave the async scheduler is a sort of dirty state (`...Task was destroyed but it is pending...`).  One other thing I'm looking for is hush logs generated (only) for non-navigational request. (I've and idea to use `getLogger('scrapy-playwright')`), not sure if it's precise though.

Thanks a lot for the help!
