### ISSUE TITLE
Is there a way to click all the same elements?

### ISSUE THREAD

**Issue by oktayozkan0** [scrapy-plugins/scrapy-playwright#123]
actually this is not an issue, its a question.
i need to scrape a booking website. there is different roomtypes in the website and different meal types for every room type. if number of meal type is larger than 3, a button appears under the room type section and i have to click all of them.

example: 3 different room types with different meal types. buttons are marked with arrows.
![booking](https://user-images.githubusercontent.com/103560387/188335083-c7fbbd3a-4a2c-4c94-8744-2ac7b642e5ca.png)

how can i handle this? 
ps: the button number is different for every hotel. if hotel does not provide different room types or meal types, the buttons may never appear.

**Comment by elacuesta** [comment]
You can [receive the Page object in the request callback](https://github.com/scrapy-plugins/scrapy-playwright#receiving-page-objects-in-callbacks) and perform arbitrary operations on it, such as [Page.click](https://playwright.dev/python/docs/api/class-page#page-click) and/or [Page.evaluate](https://playwright.dev/python/docs/api/class-page#page-evaluate). You could also perform those same operations as [PageMethods](https://github.com/scrapy-plugins/scrapy-playwright#executing-actions-on-pages).
By the way, this is not a support forum, thus questions like this one do not have high priority and might go unanswered longer than other issues (also there is no code so there's no way of telling what you have tried and what could be wrong). You might get quicker answers in more appropriate places (e.g. StackOverflow).
