### ISSUE TITLE
Sync Playwright

### ISSUE THREAD

**Issue by codejunction** [scrapy-plugins/scrapy-playwright#135]
Feature Request:

Running my crawler on a windows server.
need a sync version of the download handler

**Comment by elacuesta** [comment]
I don't see this happening, I've already given my thoughts about this on https://github.com/scrapy-plugins/scrapy-playwright/issues/2#issuecomment-763603730 - I'm not even sure what it would mean to have a sync download handler. Also, how is this related to Windows?
