### ISSUE TITLE
image dimensions is not consistent for full screen  shot 

### ISSUE THREAD

**Issue by bearxc** [scrapy-plugins/scrapy-playwright#136]
I tried doing full page screen shot as following code
    
async def parse(self, response):
        page = response.meta["playwright_page"]
         await page.screenshot(path=screenPath, full_page=True)

Our web page is pretty long  and  dimensions of  full page  image  is not keep consistent , especially on height ,  this cause problem when doing  image compare with structural_similarity, even I tried to crop with same dimensions,  structural_similarity
still detects many differences at the bottom .  If these  two screenshots have  same dimensions, then there is no difference from structural_similarity.    

Is there any workaround for that  to make sure that we could get screen shot as expected dimensions ?

I want to give a try on viewport , but do not know how to set it up yet .

**Comment by Gallaecio** [comment]
> I want to give a try on viewport , but do not know how to set it up yet .

You can see an example of that [here](https://docs.zyte.com/zyte-api/migration/browser-automation/index.html#taking-a-screenshot) (select the **scrapy-playwright** tab).

**Comment by Gallaecio** [comment]
Reopening in case I did not fully understood the issue, or viewport is not the solution.

That said, I am not sure this is a scrapy-playwright problem, but a playwright problem if anything.

**Comment by bearxc** [comment]
Thx for help ,  I agree with you , this is not scrapy-playwright problem for sure .
