### ISSUE TITLE
more info on PLAYWRIGHT_LAUNCH_OPTIONS

### ISSUE THREAD

**Issue by iRanadheer** [scrapy-plugins/scrapy-playwright#140]
Hey,

Thanks for creating this package. its really great. 

I'm facing an issue with memory, because of using playwright all the memory of my machine is getting filled and i couldn't ssh into the VM. So, I was testing few things, like changing the browsers etc. 

I couldn't find where I can find documentation on PLAYWRIGHT_LAUNCH_OPTIONS? I want to use firefox instead of chromium. 

Thanks in advance

**Comment by Gallaecio** [comment]
https://github.com/scrapy-plugins/scrapy-playwright#supported-settings points to https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch
