### ISSUE TITLE
Open new tab in non-incognito

### ISSUE THREAD

**Issue by cong235** [scrapy-plugins/scrapy-playwright#141]
Hi dev, how can I set to use launchPersistentContext to open a new tab in chrome with non-incognito mode?
I don't know what is exactly setting in scrapy-playwright plugin.
Thanks for reading

**Comment by elacuesta** [comment]
See the section on persistent contexts: https://github.com/scrapy-plugins/scrapy-playwright#persistent-contexts. Also the [contexts example](https://github.com/scrapy-plugins/scrapy-playwright/blob/main/examples/contexts.py)
