### ISSUE TITLE
scrapy-playwright does not terminate when run in CrawlerProcess

### ISSUE THREAD

**Issue by maexrakete** [scrapy-plugins/scrapy-playwright#148]
Hi,

i'm trying to use scrapy-playwright in a script, basically like this:

```python
import logging

import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings


class PlaywrightSpider(scrapy.Spider):
    name = 'Playwright'
    allowed_domains = ['google.de']
    custom_settings = {
        'DOWNLOAD_HANDLERS': {
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        }
    }

    def __init__(self, name=None, **kwargs):
        super().__init__(name, **kwargs)
        logging.getLogger("scrapy.core.engine").setLevel(logging.WARNING)
        logging.getLogger("scrapy.core.scraper").setLevel(logging.WARNING)

    def start_requests(self):
        yield scrapy.Request("https://www.google.de", meta={"playwright": True})

    def parse(self, response):
        yield {"url": response.url}


class RegularSpider(scrapy.Spider):
    name = 'Regular'
    allowed_domains = ['google.de']

    def start_requests(self):
        yield scrapy.Request("https://www.google.de")

    def parse(self, response):
        yield {"url": response.url}


if __name__ == "__main__":
    settings = get_project_settings()
    settings['TWISTED_REACTOR'] = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"

    process = CrawlerProcess(settings)

    a = process.crawl(PlaywrightSpider)
    a.addBoth(lambda x: print("I won't be printed"))

    # a = process.crawl(RegularSpider)
    # a.addBoth(lambda x: print("I will be printed"))
    process.start()
```
I added the Deferred callbacks to try to manually stop the crawler, but the one by the PlaywrightSpider never resolved.

When running it via `python main.py`, the PlaywrightSpider is executed, but not stopped. The program just gets stuck and does not terminate. When running the regular spider, everything runs as expected and the program finishes.

My first guess was, that this might be an issue with the AsyncioReactor, but the problem just appears when using the `ScrapyPlaywrightDownloadHandler`.

When calling `loop.stop()` in the `PlaywrightContextManager` I could at least stop the crawler, but the Deferred still never got called.

Hope you can help me understand what the issue is, or if this is actually a bug.

Sorry for the messy write-up, but it's late here and my python skills are also just very basic. 

Cheers!

**Comment by elacuesta** [comment]
Sorry, I cannot reproduce.
![Screenshot at 2022-12-14 22-50-44](https://user-images.githubusercontent.com/1731933/207753838-7fcbf927-2c33-4315-8493-3e7d456dc24d.png)

**Comment by elacuesta** [comment]
Closing due to lack of feedback.
