### ISSUE TITLE
block popular 3rd party resources

### ISSUE THREAD

**Issue by pouria-ariafar** [scrapy-plugins/scrapy-playwright#150]
can we also block popular 3rd party resources like tracking?
I found a [source](https://scrapfly.io/blog/web-scraping-with-playwright-and-python/) but I don't think we can use it in scrapy-playwright.

**Comment by elacuesta** [comment]
From what I'm seeing in that article, you could block said resources using [`PLAYWRIGHT_ABORT_REQUEST`](https://github.com/scrapy-plugins/scrapy-playwright#playwright_abort_request).

**Comment by Gallaecio** [comment]
Check [the documentation of the Request object](https://playwright.dev/docs/api/class-request). It includes a `url` method.
