### ISSUE TITLE
Add documentation for using scrapy playwright with CrawlSpider

### ISSUE THREAD

**Issue by amardeep** [scrapy-plugins/scrapy-playwright#157]
It is not obvious how to use playwright when using CrawlSpider rules.

**Comment by elacuesta** [comment]
Yes, I've been thinking about adding a FAQ or "How to" section, CrawlSpider being one of the first topics.

**Comment by elacuesta** [comment]
a9061d241d0fa9f088043b9033b006f39b975c36
