### ISSUE TITLE
[QUESTION] - Is there a way to tell scrapy-playwright to wait before opening more pages when concurrent total is hit? 

### ISSUE THREAD

**Issue by BenzTivianne** [scrapy-plugins/scrapy-playwright#158]
I have a spider which accesses a main webpage, and then tries to go to each of the pages listed on the main webpage. There are times where the list of new pages can exceed 50 new links. At first I was getting timeout errors and only ever able to yield 16 items. Then I found that CONCURRENT_REQUESTS was set to none and only 16 pages could be open at a time. And right before I yield the item, if I close the playwright page, I am able to get up to 24 before getting timeout errors on the new pages. 

I finally set the CONCURRENT_REQUESTS = 64 and PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT = 60 * 1000 # 60 seconds. This allows the code to run without errors but I am wondering if there is a better way to do this? 

With scrapy, it'll make 16 concurrent requests, and then wait before attempting another 16 concurrent requests. I am worried that having 50 pages open at the same time will slow down my computer. So let me know if what I am doing is the way to go or if there is a better way that I am missing. Thanks! Also, below is the code I use to open each of the new urls on the main webpage: 

```
yield scrapy.Request(
    response.urljoin(article_url), 
    self.parse_article, 
    dont_filter=self.test_dont_filter_urls, 
    meta=dict(
        playwright = True,
        playwright_include_page = True, 
        playwright_page_methods = [
            PageMethod("screenshot", full_page=True),
        ],
        errback=self.errback_close_page,
    ),
)
```
-Benz Tivianne

**Comment by elacuesta** [comment]
You are already "tell[ing] scrapy-playwright to wait before opening more pages": by updating `CONCURRENT_REQUESTS` you are indirectly setting [`PLAYWRIGHT_MAX_PAGES_PER_CONTEXT`](https://github.com/scrapy-plugins/scrapy-playwright#playwright_max_pages_per_context).
