### ISSUE TITLE
How to retry a crawling on playwright errors?

### ISSUE THREAD

**Issue by jzymx50** [scrapy-plugins/scrapy-playwright#159]
I was using the errback by scrapy, but it did not work. Seems scrapy would not handle the request returned by the callback.

```
async def errback(self, failure):
    self.logger.error(repr(failure))
    page = failure.request.meta["playwright_page"]
    await page.close()

    if failure.check(Error):
        url = failure.request.url
        yield scrapy.Request(
            url, meta=self.playwright_meta, errback=self.errback
        )
```

The error normally is `2023-01-26 13:45:11 [xx] ERROR: <twisted.python.failure.Failure playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.`

Should I use any middlewares? I'm not sure if retry middleware can catch the playwright errors. I found on the documentation it catches responses having RETRY_HTTP_CODES[¶](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#retry-http-codes)

**Comment by elacuesta** [comment]
Seems like your request is being filtered by Scrapy's [dupefilter](https://docs.scrapy.org/en/latest/topics/settings.html#dupefilter-class).

Scrapy also retries some exceptions in addition to responses with codes in `RETRY_HTTP_CODES`. It will not retry Playwright's timeouts by default, but you could try adding the exception to the [`RetryMiddleware.EXCEPTIONS_TO_RETRY`](https://github.com/scrapy/scrapy/blob/2.7.1/scrapy/downloadermiddlewares/retry.py#L131-L134) attribute:

```python
from playwright.async_api import TimeoutError as PlaywrightTimeoutError
from scrapy.downloadermiddlewares.retry import RetryMiddleware

RetryMiddleware.EXCEPTIONS_TO_RETRY += (PlaywrightTimeoutError,)
```

**Comment by Yoyoda75** [comment]
Nevermind I have tried the following implementation and it seems to be working : 

```python
from playwright.async_api import TimeoutError as PlaywrightTimeoutError
from scrapy.downloadermiddlewares.retry import RetryMiddleware

class CustomRetryMiddleware(RetryMiddleware):
        RetryMiddleware.EXCEPTIONS_TO_RETRY += (PlaywrightTimeoutError,)

        def process_response(self, request, response, spider):
            return super().process_response(request, response, spider)
```

And in my playwright spider I added the following lines : 
```python
    custom_settings: dict = {
        "SPIDER_MIDDLEWARES": {
            "CERTScrapers.middlewares.CustomRetryMiddleware": 10,
            "scrapy.spidermiddlewares.retry.RetryMiddleware": None,
            },
        }
```

I'm leaving this here for future reference, if anyone encounters the same problem I had.

**Comment by kinoute** [comment]
@Yoyoda75 Thanks for the tip! Do you really need to keep the `process_response` method in your custom retry middleware? Since we inherit from `RetryMiddleware`, it should call automatically the parent's method if it's not specified in the child class.

**Comment by elacuesta** [comment]
No need to even define a custom middleware, the code from https://github.com/scrapy-plugins/scrapy-playwright/issues/159#issuecomment-1404898624 can be pasted directly in `settings.py` or the spider file.

**Comment by Yoyoda75** [comment]
When I pasted it in the `settings.py` file directly I had the following error :
```Logtalk
Exception: The installed reactor (twisted.internet.selectreactor.SelectReactor) does not match the requested one (twisted.internet.asyncioreactor.AsyncioSelectorReactor)
```
So I figured creating a custom middleware was the best option. But if your solution works then that's great, because having to create a specific middleware just to add a single line of code isn't really efficient.

**Comment by Gallaecio** [comment]
Are you using the latest Scrapy? If so, are you importing Twisted’s `reactor` anywhere in your code?

**Comment by Yoyoda75** [comment]
I'm using Scrapy 2.5 and I'm not importing any reactor except for the `twisted.internet.asyncioreactor.AsyncioSelectorReactor` in `settings.py`. I've been looking to upgrade to the latest version but I need to make sure there are no breaking changes first.
