### ISSUE TITLE
Full list of supported PageMethod

### ISSUE THREAD

**Issue by misinglink** [scrapy-plugins/scrapy-playwright#168]
Currently only "click", "evaluate", "screenshot" are supported. 
Is there a comprehensive list of methods that are supported?
Is "evaluate" the go to for sending text to search bars?

**Comment by elacuesta** [comment]
> Currently only "click", "evaluate", "screenshot" are supported.

This is not correct, in any case, those might be the only ones shown in the examples.

> Is there a comprehensive list of methods that are supported?

Please read [the readme](https://github.com/scrapy-plugins/scrapy-playwright#supported-methods) carefully: "_Please refer to the [upstream docs for the Page class](https://playwright.dev/python/docs/api/class-page) to see available methods._"

> Is "evaluate" the go to for sending text to search bars?

I haven't tried `Page.evaluate` for that myself, but I suppose it should work with something like `document.getElementById("input-id").value = "search-term";`. In the past I have used [`Page.fill`](https://playwright.dev/python/docs/api/class-page#page-fill), but now I'm seeing it's deprecated in favor of [`Locator.fill`](https://playwright.dev/python/docs/api/class-locator#locator-fill). `Locator.fill` should work by [handling the page object in the callback](https://github.com/scrapy-plugins/scrapy-playwright#receiving-page-objects-in-callbacks).
