### ISSUE TITLE
can't get anything from scrapy items

### ISSUE THREAD

**Issue by Edmounds** [scrapy-plugins/scrapy-playwright#170]
here are my code
`    def parse_text(self, response):
        total_lou = response.xpath('//div[@class="l_post l_post_bright j_l_post clearfix  "]')
        item = TiebaItem()

        for lou in total_lou:
            text = lou.xpath('.//div[@class="d_post_content j_d_post_content "]/text()').extract_first()
            region = lou.xpath('.//div[@class="post-tail-wrap"]/text()').extract_first()
            date = lou.xpath('.//span[@class="tail-info"][position()=3]/text()').extract_first()
            reply_text = lou.xpath('.//span[@class="lzl_content_main"]/text()').extract_first()
            reply_date = lou.xpath('.//span[@class="lzl_time"]/text()').extract_first()

            # can't find in the log
            print('='*100)

            item['text'] = text
            item['region'] = region
            item['date'] = date
            item['reply_text'] = reply_text
            item['reply_date'] = reply_date
            yield item

    async def parse(self, response):
        page = response.meta["playwright_page"]
        await self.scroll_reply(page)
        await page.screenshot(path="output.png", full_page=True)
        body_str = await page.content()
        new_response = response.replace(body=body_str)
        await page.close()

        self.parse_text(new_response)
`

i can't get anything form the response,from the log i found that the'parse_text' function is  not working,because i didnt find '='*100 in the log.

**Comment by elacuesta** [comment]
`parse_text` is a generator but you're not iterating over it (generators are evaluated lazily). Moreover, you're creating the item outside of the `for` loop so all items would be the same object.
