### ISSUE TITLE
[QUESTION]Is there a way to make `is_visble()` detect a region that i set instead of the whole page.

### ISSUE THREAD

**Issue by Edmounds** [scrapy-plugins/scrapy-playwright#172]
In the page,there are many parts,and every part has an element which has the same class(other args are complicated.Meanwhile,i need to use 
```
  bounding = await locate.bounding_box()
  x = bounding['x']
  y = bounding['y']
  wait page.evaluate(f'window.scrollBy({x}, {y})')
```
to locate the elements one by one and wait.becaunse the element is invisible at the beginning.At the first time,i use `time.sleep()`.However, this method is not flexible, because the waiting time is fixed, but fluctuations in Internet speed in actual use will have a great impact and this method will not meet expectations.

The question came`is_visble()` in the doc,I have used this method but it doesn't work as expected.From the perspective of the entire page, this method detects elements of the entire page,so it doesn't wait the rest elements.

Is there a way to make `is_visble()` detect a region that i set instead of the whole page.
I would appreciate it if you could provide a workaround

**Comment by elacuesta** [comment]
This looks like a question about how to use Playwright itself, not scrapy-playwright. I'd suggest looking into their support resources, a good place to start would be https://playwright.dev/python/community/welcome.
