### ISSUE TITLE
scrapy-playwright & Selenium Grid

### ISSUE THREAD

**Issue by akrbout** [scrapy-plugins/scrapy-playwright#173]
I want to try using Selenium Grid with scrapy-playwright. Is there any way to set up such a process or does anyone have any experience with this?

**Comment by elacuesta** [comment]
I have zero experience with Selenium, I will not be providing support on this thread.
I will leave the issue open for some time in case someone else can share their thoughts.

**Comment by akrbout** [comment]
Okay, I found a solution to my problem, I'll leave it below for those who also want to use [Selenium Grid](https://www.selenium.dev/documentation/grid/) along with _scrapy-playwright_.

And the solution is pretty simple - in the spiders settings we enter the necessary variables for Playwright startup.
In global settings (`settings.py`):
```
os.environ["SELENIUM_REMOTE_URL"] = "http://<selenium-hub-ip>:4444/wd/hub"
os.environ["DEBUG"] = "pw:browser*"
```

The solution is a little dumb, but it works for me.

**Comment by elacuesta** [comment]
See also https://playwright.dev/docs/selenium-grid
