### ISSUE TITLE
stuck in blank page after a period of time.

### ISSUE THREAD

**Issue by dragospopa420** [scrapy-plugins/scrapy-playwright#174]
Context:

- OS : MacOS 13.1
-  Python (venv) : Python 3.8.16
-  scrapy-playwright : 0.0.25 (playwright 1.30.0)

Issue:
I've tried with all 3 drivers, chromium, webkit, firefox.
After some hours of scraping, the scraper goes randomly into a blank page and it doesn't get out of there (It's not getting blocked or anything).
I would post the logs but no errors occur, no warnings no nothing, I see all the requests and at one point they stop appearing and I only get scrapy logstats and the browser remains stuck on a blank page.

For me it seems like it's just "disconnecting" from the code somehow.
I've had some errors from the playwright engine regarding the memory, so I've forced garbage collection, after that I've checked with Muppy, and maximum memory that I've saw used was 40-50mb.

Sample code: 
I've ommited the parse_products function because it's just processing the DOM and returns a dict with the product that I'm yielding.

```python
class XSpider(scrapy.Spider):
    name = "x_spider"
    allowed_domains = ['x_domain.es']
    start_urls = []

    CUSTOM_PIPELINES = ITEM_PIPELINES.copy()
    CUSTOM_PIPELINES['myproject.pipelines.mypipeline'] = 300
    CUSTOM_DOWNLOADER_MIDDLEWARES = DOWNLOADER_MIDDLEWARES.copy()
    CUSTOM_DOWNLOADER_MIDDLEWARES.update({
        'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': 400,
        'scrapy_user_agents.middlewares.RandomUserAgentMiddleware': None,
        'tor_ip_rotator.middlewares.TorProxyMiddleware': None,
    })

    custom_settings = {

        'FEED_FORMAT': 'csv',
        'FEED_EXPORT_FIELDS': constants.daily_scraper_feed_format,
        'ITEM_PIPELINES': CUSTOM_PIPELINES,
        'DOWNLOADER_MIDDLEWARES': CUSTOM_DOWNLOADER_MIDDLEWARES,
        'DOWNLOAD_HANDLERS': {
            # "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
        'TWISTED_REACTOR': "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        'USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0',
        'RETRY_TIMES': 5,
        'RETRY_HTTP_CODES': RETRY_HTTP_CODES + [403, 407],
        'CONCURRENT_REQUESTS': 2,
        'PLAYWRIGHT_LAUNCH_OPTIONS': {
            "headless": False,
            "timeout": 6 * 1000,  # 6 seconds
        },
        'PLAYWRIGHT_MAX_CONTEXTS': 1,
        'PLAYWRIGHT_MAX_PAGES_PER_CONTEXT': 2,
        'PLAYWRIGHT_CONTEXTS': {
            "persistent": {
                "user_data_dir": "persistent_ctx",  # will be a persistent context
                "viewport": {'width': 1280, 'height': 6000},
            },
        },
        'PLAYWRIGHT_BROWSER_TYPE': "chromium"
    }

    def start_requests(self):
          for url in self.start_urls:
              yield scrapy.Request(url=url,
                                 callback=self.parse,
                                 meta={"playwright": True, "playwright_include_page": True,
                                       "playwright_context": "persistent"},
                                 )
        gc.collect()

    @loguru.logger.catch
    async def parse(self, response):
         page = response.meta.get('playwright_page')
         products_count = await page.locator('.product-card__title a').count()
        print(f'products_count:{products_count}')
        gc.collect()
        if products_count:
            for i in range(products_count):
                product = await self.playwright_engine(locator=page.locator('.product-card__title a').nth(i), page=page)
                yield product
                del product
            else:
                await page.close()
                if response.css('div.pagination__row a::attr(href)'):
                    next_page_short = response.css('div.pagination__row a::attr(href)').getall()[-1]
                    print(next_page_short)
                    yield scrapy.Request(url=f'{self.domain_url}{next_page_short}',
                                         callback=self.parse,
                                         meta={"playwright": True, "playwright_include_page": True,
                                               "playwright_context": "persistent"},
                                         )
                del response
                gc.collect()

   @loguru.logger.catch
    async def playwright_engine(self, locator, page):

        if await self.retry_async(locator.click, 50):
            # await self.retry_async(page.wait_for_load_state, 5)
            data = await page.content()
            product = self.parse_products(data=data, prod_url=page.url)
            await self.retry_async(page.go_back, 50)

            del locator
            gc.collect()

            return product

    @loguru.logger.catch
    async def retry_async(self, func, max_retries):
        """
        Takes as input a playwright function without await and the number of retries.
        """
        success = False
        retries = 0
        while not success and retries < max_retries:
            try:
                await func()
                success = True
            except (PlaywrightTimeout, PlaywrightError):
                retries += 1

        gc.collect()

        return success  
```

**Comment by maciek85k** [comment]
I have a similar issue. The only difference is that I'm stuck on this page
![[Challenge Validation](https://i.stack.imgur.com/1r5bB.png)](https://user-images.githubusercontent.com/124876132/217774631-2288f0e2-3097-46cf-98e6-fd25aaae5390.png) instead of a blank page. 
I would like to know how it is possible to reload the page. So I can catch the error.

**Comment by maciek85k** [comment]
I have found a solution to my problem. 
See: Usage with scrapy-proxies at this site: 
https://github.com/alecxe/scrapy-fake-useragent#usage-with-scrapy-proxies

**Comment by elacuesta** [comment]
Given the fact that most of the processing is done by directly manipulating Playwright pages, I'd recommend verifying that the issue does not happen with standalone Playwright.
Regarding the second report about proxies, I don't see how it is related to the original question.

**Comment by dragospopa420** [comment]
It does not happen with standalone playwright.
I've moved the project to Node, and this also improved the memory leaks a lot.

**Comment by 0x66656c6978** [comment]
I'm noticing the same behaviour. After about 50 minutes of crawling, I only see the scrapy log stats output. No errors. When I check the chrome_debug.log in the chrome_user_data directory, I can see that it is still running and crawling pages, even an hour later, but there is no output in scrapy.

**Comment by GitHubForLiuQiao** [comment]
> chrome_user_data

Did you solve the problem? I have a similar problem.

**Comment by GitHubForLiuQiao** [comment]
> I'm noticing the same behaviour. After about 50 minutes of crawling, I only see the scrapy log stats output. No errors. When I check the chrome_debug.log in the chrome_user_data directory, I can see that it is still running and crawling pages, even an hour later, but there is no output in scrapy.
Did you solve the problem? I have a similar problem.
