### ISSUE TITLE
Overridden method for Playwright request to <URL> original=POST new=GET

### ISSUE THREAD

**Issue by Cooperrr** [scrapy-plugins/scrapy-playwright#176]
I have a site that executes javascript when a button is clicked, `javascript:__doPostBack('ctl00$ContentPlaceHolder1$grvLey','Select$0');return false;`

This javascript executes a POST request to the current url with a dynamically generated body which the site then responds with the new page. However when I click on the button with Scrapy-playwright handler.py is changing the POST request to a GET request, how can I allow this POST request to go through without Scrapy-Playwright overriding it?

**Comment by Cooperrr** [comment]
Figured out I needed to set the method of the original request to the page as post, as well as setting 
`"PLAYWRIGHT_PROCESS_REQUEST_HEADERS": None,` to give playwright complete control over the headers

**Comment by elacuesta** [comment]
I actually think this is a valid concern, even if the initial request is GET the method should not be overridden if the request is triggered by a Playwright action.

Header processing should not be relevant in this case: [it is done before](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.26/scrapy_playwright/handler.py#L487-L494) and it does not play any role in deciding whether or not to [override the method](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.26/scrapy_playwright/handler.py#L502-L504).

**Comment by Cooperrr** [comment]
Agreed, it would be a nice addition to not override the method in this instance. 

Apologies, you are correct. Without setting the PLAYWRIGHT_PROCESS_REQUEST_HEADERS to None the method is no longer overridden. I mistook the fact that the page I am scraping does not update without giving control of the headers to Scrapy-playwright to be linked to the method being overridden.
