### ISSUE TITLE
Can I use launch_persistent_context in scrapy-playwright with headless=False?

### ISSUE THREAD

**Issue by fhlemos** [scrapy-plugins/scrapy-playwright#178]
Is it possible to use persistent context with headless browser false?

I'm using this setup, but the browser does not run.

```
PLAYWRIGHT_LAUNCH_OPTIONS = {
    "headless": False,
    "devtools": False,
    "args": [
        "--disable-extensions-except=/home/user/metamask-chrome/metamask",
        "--load-extension=/home/user/metamask-chrome/metamask"
    ]
}
```
`PLAYWRIGHT_CONTEXTS = {"persistent": {"user_data_dir": str(Path.home() / "playwright-persistent-context")}}`

**Comment by sliverc** [comment]
I have the exact same problem when I set a `user_data_dir` in the playwright context even though `headless` is `False` the browser window does not open/show. When I do not set the `user_data_dir` the browser shows without any difficulties. Anyone has an idea how to change the configuration so it works in headed mode with a user data dir?

**Comment by sliverc** [comment]
I had a closer look at the code to figure out what was going on. It looks like when using persistent mode, the `PLAYWRIGHT_LAUNCH_OPTIONS` setting is completely ignored. Instead, those options need to be added to the persistent context.

I used the following:

```python
"PLAYWRIGHT_CONTEXTS": {
    "persistent": {
        "headless": False,
        "devtools": False,
        "user_data_dir": str(Path.home() / "playwright-persistent-context"),
        "args": [
            "--disable-extensions-except=/home/user/metamask-chrome/metamask",
            "--load-extension=/home/user/metamask-chrome/metamask"
        ],
    }
},
```

With this setting, the browser shows up including the extension. Maybe this is something to mention in the docs for how to configure a persistent context.

**Comment by elacuesta** [comment]
That's correct, persistent contexts are launched directly from the BrowserType ([`BrowserType.launch_persistent_context`](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context)) without launching a browser instance first. I'm treating this as a documentation request then, to clarify this behavior in the README. Thank you for the research @sliverc.

**Comment by elacuesta** [comment]
78282b56ea745f4dc6c20c33cea35acb98a78054
