### ISSUE TITLE
Not able to click a link with href=#

### ISSUE THREAD

**Issue by supermario18b** [scrapy-plugins/scrapy-playwright#180]
Hi everyone,

I'm not able to click a link in a \<a\> tag. I don't see any errors but I can't see any change in the html source code.
After clicking the link with xpath "//li[@class="webradio "]/a" the class "active" should be enabled but nothing happens.
The href points to # and there is an event listener that changes the source code. 

`
import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.selector import Selector

class TestSpider(scrapy.Spider):
    name = 'login'
 
    def start_requests(self):
        yield scrapy.Request(
            "https://www.radioitalia.it",
            meta={
                "playwright": True,
                "playwright_include_page": True,
            }
        )
 
    async def parse(self, response):
        page = response.meta["playwright_page"]
        #accept cookies
        await page.locator('xpath=//button[@mode="primary"]').click()
        #switch to webradio
        await page.locator('xpath=//li[@class="webradio "]/a').click()
        html_content = await page.inner_html("body")
        
        body = Selector(text=html_content)

        await page.close()

        yield {
            #the button webradio should obtain the "active" class but nothing happens
            "body": body.xpath('//ul[@class="radio-buttons"]').getall()
        }

process = CrawlerProcess(settings={
        #'LOG_ENABLED': False,
        'DOWNLOAD_HANDLERS': {
            'http': 'scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler',
            'https': 'scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler',
        },
        'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor',
})

process.crawl(TestSpider)
process.start()

`

Could you please point me to the right direction?

Thanks in advance,

supermario18b

**Comment by elacuesta** [comment]
You are doing all of your page manipulation using Playwright directly, it doesn't seem to be a problem with this Scrapy integration. I'd suggest trying with standalone Playwright and/or adding some `Page.wait_for_timeout`/`Page.wait_for_selector` call.

**Comment by supermario18b** [comment]
> You are doing all of your page manipulation using Playwright directly, it doesn't seem to be a problem with this Scrapy integration. I'd suggest trying with standalone Playwright and/or adding some `Page.wait_for_timeout`/`Page.wait_for_selector` call.

Thanks for your advice,  it came out that the problem was using the standard browser of playwright (chromium). I tried with firefox and it worked.
