### ISSUE TITLE
Referer seems override by assets requests

### ISSUE THREAD

**Issue by kinoute** [scrapy-plugins/scrapy-playwright#181]
Hello,

I like to set and save a Referer when I'm crawling a page. When I make a request through Scrapy/Playwright with a Referer set like this:

```python3
  'playwright_page_goto_kwargs': {
      'referer': 'https://defret.in',
  }
```

The Referer I'm getting through `response.request.headers.get('Referer')` once the crawling is done is different / override by the downloading of the assets of the page, see the crawling:

```
[Context=custom] New page created, page count is 1 (1 for all contexts)
[Context=custom] Request: <GET https://defret.in/> (resource type: document, referrer: https://defret.in/)
[Context=custom] Response: <200 https://defret.in/> (referrer: None)
[Context=custom] Request: <GET https://defret.in/assets/css/main.css> (resource type: stylesheet, referrer: https://defret.in/)
[Context=custom] Response: <200 https://defret.in/assets/css/main.css> (referrer: None)
[Context=custom] Request: <GET https://defret.in/assets/fonts/wotfard/wotfard-semibold-webfont.woff2> (resource type: font, referrer: https://defret.in/assets/css/main.css)
[Context=custom] Request: <GET https://defret.in/assets/fonts/wotfard/wotfard-regular-webfont.woff2> (resource type: font, referrer: https://defret.in/assets/css/main.css)
[Context=custom] Request: <GET https://defret.in/assets/fonts/leaguemono/LeagueMono-Regular.woff2> (resource type: font, referrer: https://defret.in/assets/css/main.css)
Crawled (200) <GET https://defret.in/> (referer: https://defret.in/assets/css/main.css) ['playwright']
[Context=custom] Response: <200 https://defret.in/assets/fonts/wotfard/wotfard-semibold-webfont.woff2> (referrer: None)
[Context=custom] Response: <200 https://defret.in/assets/fonts/wotfard/wotfard-regular-webfont.woff2> (referrer: None)
[Context=custom] Response: <200 https://defret.in/assets/fonts/leaguemono/LeagueMono-Regular.woff2> (referrer: None)
````

`response.request.headers.get('Referer')` returns:

```
https://defret.in/assets/css/main.css
```

Is it a normal behavior? I was using this method to save the "source" of the page, i.e from where I found a link for the given page. I think I can find easily a workaround to not use `response.request` but I was just wondering if it's normal as it works correctly in "classic" Scrapy mode.

I did try to use the `headers` arguments in `Scrapy.Request` like I do in the "classic" Scrapy mode without Playwright but since I have `PLAYWRIGHT_PROCESS_REQUEST_HEADERS` set to `None`, the Referer is not passed.

Thank you!

**Comment by elacuesta** [comment]
You are correct, headers included in the request that reached the callback were being overridden with headers from asset requests. Thanks for the report.
