### ISSUE TITLE
Unable to retrieve content because the page is navigating and changing the content

### ISSUE THREAD

**Issue by 0x66656c6978** [scrapy-plugins/scrapy-playwright#186]
Occasionally the following error occurs. 

```
Traceback (most recent call last): 
File "CENSORED/lib/python3.8/site-packages/twisted/internet/defer.py", line 1693,
in _inlineCallbacks result  = context.run( File "CENSORED/lib/python3.8/site-packages/twisted/python/failure.py", line 518,
in throwExceptionIntoGenerator return g.throw(self.type, self.value, self.tb) File "CENSORED/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 52,
in process_request return (yield download_func(request=request, spider=spider)) File "CENSORED/lib/python3.8/site-packages/twisted/internet/defer.py", line 1065,
in adapt extracted = result.result() File "CENSORED/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 297,
in _download_request result = await self._download_request_with_page(request, page, spider) File "CENSORED/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 350,
in _download_request_with_page body_str = await page.content() File "CENSORED/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 9063,
in content return mapping.from_maybe_impl(await self._impl_obj.content()) File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_page.py", line 477,
in content return await self._main_frame.content() File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 415,
in content return await self._channel.send("content") File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44,
in send return await self._connection.wrap_api_call( File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419,
in wrap_api_call return await cb() File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79,
in inner_send result = next(iter(done)).result()
playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.
```

Looking at the same issue in playwright, they recommend retrying to access the content: https://github.com/microsoft/playwright/issues/20483

**Comment by alfred-liu96** [comment]
> Occasionally the following error occurs.
> 
> ```
> Traceback (most recent call last): 
> File "CENSORED/lib/python3.8/site-packages/twisted/internet/defer.py", line 1693,
> in _inlineCallbacks result  = context.run( File "CENSORED/lib/python3.8/site-packages/twisted/python/failure.py", line 518,
> in throwExceptionIntoGenerator return g.throw(self.type, self.value, self.tb) File "CENSORED/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 52,
> in process_request return (yield download_func(request=request, spider=spider)) File "CENSORED/lib/python3.8/site-packages/twisted/internet/defer.py", line 1065,
> in adapt extracted = result.result() File "CENSORED/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 297,
> in _download_request result = await self._download_request_with_page(request, page, spider) File "CENSORED/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 350,
> in _download_request_with_page body_str = await page.content() File "CENSORED/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 9063,
> in content return mapping.from_maybe_impl(await self._impl_obj.content()) File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_page.py", line 477,
> in content return await self._main_frame.content() File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 415,
> in content return await self._channel.send("content") File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44,
> in send return await self._connection.wrap_api_call( File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419,
> in wrap_api_call return await cb() File "CENSORED/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79,
> in inner_send result = next(iter(done)).result()
> playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.
> ```
> 
> Looking at the same issue in playwright, they recommend retrying to access the content: [microsoft/playwright#20483](https://github.com/microsoft/playwright/issues/20483)

I'm running into this error too, how did you solve it?

**Comment by alfred-liu96** [comment]
Finally I found out that adding a wait_for function can solve this problem
