### ISSUE TITLE
Scrapy callback not executing and is never reached

### ISSUE THREAD

**Issue by Jackie247** [scrapy-plugins/scrapy-playwright#194]
For some context, I have a spider which purpose is to crawl a website that relies on JavaScript for rendering. My spider includes two asynchronous functions, parse_categories and parse_product_page.

The parse_categories function checks for categories in the URL and sends requests to the parse_categories callback again until a product page is found which should be when no categories are found. If no categories are found, it should send a request to the parse_product_page callback.

However, when it reaches the else block in parse_categories, it seems that the request to parse_product_page is never made. I've confirmed that the code enters the else block, but the print statement in the parse_product_page function is never reached.

Below is a minimal reprex with the same problem

Reprex:

```
import scrapy
from scrapy_playwright.page import PageMethod

class Spider():
    name = "quotes"
    allowed_domains = ['quotes.toscrape.com']

  
    def start_requests(self):
        yield scrapy.Request(url='https://quotes.toscrape.com/js/', callback=self.parse_urls, 
              meta=dict(
                   playwright = True, 
                   playwright_include_page = True,
                   playwright_page_methods = [
                         PageMethod('wait_for_selector','body > div > nav > ul > li > a')
                        ],
                   ))
    

    async def parse_urls(self, response):
        page = response.meta['playwright_page']
        await page.close()
        
        next_page_url = response.xpath('//li[@class="next"]/a/@href').get()

        if next_page_url:
            print("Inside if block")
            url = 'https://quotes.toscrape.com' + next_page_url
            yield scrapy.Request(url=url,callback=self.parse_urls,
                meta=dict(
                    playwright = True,
                    playwright_include_page = True,
                    playwright_page_methods = [
                        PageMethod('wait_for_selector','body > div > div.quote')]
                        ))
        else:
            print("Next page link not found")
            yield scrapy.Request(url=response.request.url, callback=self.parse, 
                    meta=dict(
                        playwright = True,
                        playwright_include_page = True,
                        playwright_page_methods = [
                            PageMethod('wait_for_selector','body > div > div.quote')]
                        ))


    async def parse(self,response):
        page = response.meta['playwright_page']
        await page.close()
        print("Function has been called, because next page link not found")
```
Below is the output logs after running the crawler:

> Inside if block
Inside if block
Inside if block
Inside if block
Inside if block
Inside if block
Inside if block
Inside if block
Inside if block
Next page link not found
2023-04-11 09:47:04 [root] WARNING: spider quotes finished crawling

As you can see, the print statement in parse function is never reached.

**Comment by Laerte** [comment]
HI @Jackie247 

Justed tested ir our snippet, had to add to inherit to `scrapy.Spider` on Spider because i was receiving: 
> KeyError: 'Spider not found: quotes'

```python
class Spider(scrapy.Spider):
```

After fixing this first issue i noticed that the the Request was not being made because of duplicate filter:
```
Next page link not found
2023-04-14 05:57:05 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://quotes.toscrape.com/js/page/10/> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
```

I just add `dont_filter=True` to `Request` in else statement and spider runned successfully:

```
2023-04-14 05:58:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://quotes.toscrape.com/js/page/10/> (referer: https://fonts.googleapis.com/) ['playwright']
Function has been called, because next page link not found
```

**Comment by Jackie247** [comment]
Brilliant, that has solved the issue. Thanks so much!
