### ISSUE TITLE
Handler using sync Playwright APIs

### ISSUE THREAD

**Issue by nichoi** [scrapy-plugins/scrapy-playwright#2]
Hi, I noticed that Playwright offers two APIs - one synchronous and one asynchronous.

It seems the handler you wrote is tied to the asynchronous API.

For my project, I plan to write an equivalent handler that uses the synchronous API. Do you think writing this synchronous handler would be possible? (I plan to not use the AsyncioSelectorReactor reactor)

Thank you!

**Comment by elacuesta** [comment]
I suppose it should be possible, although I believe that would defeat the purpose of Scrapy, which is an asynchronous framework. What is your use case?
Keep in mind that the synchronous API also [uses `asyncio` internally](https://github.com/microsoft/playwright-python/blob/v0.171.1/playwright/_main.py#L59). I haven't tested it, but I'm not sure exactly how that would work with non-asyncio Twisted reactors.
