### ISSUE TITLE
remote chrome support

### ISSUE THREAD

**Issue by llonchj** [scrapy-plugins/scrapy-playwright#207]
I am new to scrapy-playwright.

I want to scrape using chrome on a remote machine as explained in https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html and using `playwright.chromium.connect_over_cdp`.

Here is a working snippet:

```python
from playwright.sync_api import sync_playwright


with sync_playwright() as playwright:
    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")

    page = browser.new_page()
    page.goto("https://example.com")
    print(page.title())
    browser.close()
```

What is the best way to use scrapy-playwright using a remote machine?

Thanks!

**Comment by elacuesta** [comment]
This is not possible at the moment. Currently the browser is closed when the crawl finishes, that might not be desired if the browser is remote.
Sounds like a good feature to have, thanks for the request.

**Comment by wuchang** [comment]
期待这个功能

**Comment by elacuesta** [comment]
Support for connecting to a remote browser via the Chrome DevTools Protocol was added in version [0.0.32](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.32). See the docs for the [PLAYWRIGHT_CDP_URL](https://github.com/scrapy-plugins/scrapy-playwright#playwright_cdp_url) and [PLAYWRIGHT_CDP_KWARGS](https://github.com/scrapy-plugins/scrapy-playwright#playwright_cdp_kwargs) settings.
