### ISSUE TITLE
RAM usage question

### ISSUE THREAD

**Issue by andrei-volkau** [scrapy-plugins/scrapy-playwright#209]
I have one question about RAM usage. 

<img width="1280" alt="Screenshot 2023-07-16 at 15 36 37" src="https://github.com/scrapy-plugins/scrapy-playwright/assets/12778567/0437e584-f7ff-4c86-9096-949bdff523ab">

My scrapy code is not executing anymore, but I am still able to see that RAM is being consumed by playwright. 
What should I do to avoid all RAM to be consumed by paywirght even so that scraping process is not running any more? Should I find and kill playwright processes on Spider closed event? 

I was having a lot of playwright timeouts during scraping. Maybe I experienced memory leaks?

**Comment by elacuesta** [comment]
A good catch, thank you for noticing.
