### ISSUE TITLE
How to add cookies for context?

### ISSUE THREAD

**Issue by CookiesEason** [scrapy-plugins/scrapy-playwright#21]
The code:
```
scrapy.Request(
            url=url,
            cookies=cookies,
            ...
)
```
It is not available.
But I use this method:`await page.context.add_cookies(cookies=c)` in parse, it is available, but this method is too bad.

**Comment by elacuesta** [comment]
Sending cookies using the `Request.cookies` argument does work, please check the [`examples/cookies.py`](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.4/examples/cookies.py) script.
An alternative could be to pass `storage_state.cookies` ([see this page for reference](https://playwright.dev/python/docs/api/class-browser/#browser-new-context))  when creating the browser contexts (either at startup with the `PLAYWRIGHT_CONTEXTS` setting or during a crawl with the `playwright_context_kwargs` request  meta key).
