### ISSUE TITLE
Unused 'spider' parameter in '_create_browser_context' method

### ISSUE THREAD

**Issue by lishukan** [scrapy-plugins/scrapy-playwright#211]
<img width="707" alt="image" src="https://github.com/scrapy-plugins/scrapy-playwright/assets/23066239/f06f7180-7967-455c-bbe1-5a18abec14f6">

_create_browser_context  has a parameter named 'spider' ,is optional。
But is handler.py,  you can find that  the spider parameter never receive  a value when called.

<img width="762" alt="image" src="https://github.com/scrapy-plugins/scrapy-playwright/assets/23066239/8ba4ae3f-bb26-4e05-9c8d-7ec9326121f2">

**Comment by elacuesta** [comment]
A good catch, thank you.
