### ISSUE TITLE
How can I shield the debug log or how can I customize the log level ??

### ISSUE THREAD

**Issue by sick-pupil** [scrapy-plugins/scrapy-playwright#230]
When I run my program, there is too many debug log printed out

**Comment by elacuesta** [comment]
This package uses [standard Python logging](https://docs.python.org/3/howto/logging.html). Logging can also be configured at the [Scrapy level](https://docs.scrapy.org/en/latest/topics/logging.html), see the [LOG_LEVEL](https://docs.scrapy.org/en/latest/topics/settings.html#std-setting-LOG_LEVEL) setting and the related [command line options](https://docs.scrapy.org/en/latest/topics/logging.html#command-line-options).

**Comment by sick-pupil** [comment]
Thanks
