### ISSUE TITLE
 Need Help Configuring the "wait_until" kwarg in Scrapy-Playwright

### ISSUE THREAD

**Issue by LoyAngel** [scrapy-plugins/scrapy-playwright#232]
In my project, I'm trying to configure the "wait_until" kwarg while using "scrapy.Request." However, despite thoroughly reviewing the documentation for Scrapy, Playwright, and Scrapy-playwright, I haven't been able to find any helpful information. Could someone assist me in resolving this issue? Thank you for your help.

log:
``` 
2023-09-12 13:27:03 [root] ERROR: Something seems wrong, request=<GET http://www.gwytb.gov.cn/zt/zylszl/92/>, exception=TimeoutError('Timeout 60000ms exceeded.\n=========================== logs ===========================\nnavigating to "http://www.gwytb.gov.cn/zt/zylszl/92/", waiting until "load"\n============================================================')

2023-09-12 13:27:03 [root] INFO: {'proxy_str': None, 'playwright': True, 'playwright_include_page': True, 'playwright_context': UUID('dd5c7894-512c-11ee-83b6-525400721332'), 'playwright_context_kwargs': {}, 'playwright_page_goto_kwargs': {'wait_until': 'commit'}, 'download_timeout': 60000.0, 'download_slot': 'www.gwytb.gov.cn'}
```

code:
```python
@staticmethod
def build_request(url, cookies=None, proxy_str=None, account_id=None, error_back=None, set_blank=False) -> scrapy.Request:
    request_meta = {
        "proxy_str": proxy_str,
        "playwright": True,
        "playwright_include_page": True,
        "playwright_context": uuid.uuid1(),
        "playwright_context_kwargs": {},
        "playwright_page_goto_kwargs": {
            "wait_until": "commit", # This didn't work. T_T
        }
   }
    return scrapy.Request(url, cookies=cookies, meta=request_meta, dont_filter=True, errback=error_back)
```

**Comment by elacuesta** [comment]
I'm sorry, I cannot reproduce with [v0.0.32](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.32). Full example:

```python
import uuid
import scrapy

class CommitSpider(scrapy.Spider):
    name = "commit"
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "DOWNLOAD_HANDLERS": {
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
        "PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT": 100,
    }

    @staticmethod
    def build_request(
        url, cookies=None, proxy_str=None, account_id=None, error_back=None, set_blank=False
    ) -> scrapy.Request:
        request_meta = {
            "proxy_str": proxy_str,
            "playwright": True,
            "playwright_include_page": True,
            "playwright_context": uuid.uuid1(),
            "playwright_context_kwargs": {},
            "playwright_page_goto_kwargs": {"wait_until": "commit"},
        }
        return scrapy.Request(
            url, cookies=cookies, meta=request_meta, dont_filter=True, errback=error_back
        )

    def start_requests(self):
        yield self.build_request("https://httpbin.org/delay/10")

    def parse(self, response):
        yield {"url": response.url}
```

```
2023-09-12 08:38:09 [scrapy.core.engine] INFO: Spider opened
2023-09-12 08:38:09 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-09-12 08:38:09 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-09-12 08:38:09 [scrapy-playwright] INFO: Starting download handler
2023-09-12 08:38:14 [scrapy-playwright] INFO: Launching browser chromium
2023-09-12 08:38:14 [scrapy-playwright] INFO: Browser chromium launched
2023-09-12 08:38:14 [scrapy-playwright] DEBUG: Browser context started: 'dc2d0bfd-5160-11ee-ba69-94c6911285da' (persistent=False, remote=False)
2023-09-12 08:38:15 [scrapy-playwright] DEBUG: [Context=dc2d0bfd-5160-11ee-ba69-94c6911285da] New page created, page count is 1 (1 for all contexts)
2023-09-12 08:38:15 [scrapy-playwright] DEBUG: [Context=dc2d0bfd-5160-11ee-ba69-94c6911285da] Request: <GET https://httpbin.org/delay/10> (resource type: document)
2023-09-12 08:38:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://httpbin.org/delay/10>
Traceback (most recent call last):
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/internet/defer.py", line 1065, in adapt
    extracted = result.result()
  File "/scrapy-playwright/scrapy_playwright/handler.py", line 322, in _download_request
    result = await self._download_request_with_page(request, page, spider)
  File "/scrapy-playwright/scrapy_playwright/handler.py", line 357, in _download_request_with_page
    response = await page.goto(url=request.url, **page_goto_kwargs)
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9251, in goto
    await self._impl_obj.goto(
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_page.py", line 479, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 100ms exceeded.
=========================== logs ===========================
navigating to "https://httpbin.org/delay/10", waiting until "commit"
============================================================
2023-09-12 08:38:15 [scrapy.core.engine] INFO: Closing spider (finished)
```

The keyword argument is being used correctly in the `Page.goto` call. Notice that if you pass an incorrect argument name you get:
```
TypeError: Page.goto() got an unexpected keyword argument 'incorrect_key'
```
and if you pass an incorrect value for `wait_until` you get:
```
playwright._impl._api_types.Error: wait_until: expected one of (load|domcontentloaded|networkidle|commit)
```

**Comment by LoyAngel** [comment]
I suspect it might be a version issue. We are using version 0.0.5. Could it be that the "wait_until" parameter hasn't been enabled yet?

**Comment by LoyAngel** [comment]
> I'm sorry, I cannot reproduce with [v0.0.32](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.32). Full example:
> 
> 
> 
> ```python
> 
> import uuid
> 
> import scrapy
> 
> 
> 
> class CommitSpider(scrapy.Spider):
> 
>     name = "commit"
> 
>     custom_settings = {
> 
>         "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
> 
>         "DOWNLOAD_HANDLERS": {
> 
>             "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
> 
>         },
> 
>         "PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT": 100,
> 
>     }
> 
> 
> 
>     @staticmethod
> 
>     def build_request(
> 
>         url, cookies=None, proxy_str=None, account_id=None, error_back=None, set_blank=False
> 
>     ) -> scrapy.Request:
> 
>         request_meta = {
> 
>             "proxy_str": proxy_str,
> 
>             "playwright": True,
> 
>             "playwright_include_page": True,
> 
>             "playwright_context": uuid.uuid1(),
> 
>             "playwright_context_kwargs": {},
> 
>             "playwright_page_goto_kwargs": {"wait_until": "commit"},
> 
>         }
> 
>         return scrapy.Request(
> 
>             url, cookies=cookies, meta=request_meta, dont_filter=True, errback=error_back
> 
>         )
> 
> 
> 
>     def start_requests(self):
> 
>         yield self.build_request("https://httpbin.org/delay/10")
> 
> 
> 
>     def parse(self, response):
> 
>         yield {"url": response.url}
> 
> ```
> 
> 
> 
> ```
> 
> 2023-09-12 08:38:09 [scrapy.core.engine] INFO: Spider opened
> 
> 2023-09-12 08:38:09 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> 
> 2023-09-12 08:38:09 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
> 
> 2023-09-12 08:38:09 [scrapy-playwright] INFO: Starting download handler
> 
> 2023-09-12 08:38:14 [scrapy-playwright] INFO: Launching browser chromium
> 
> 2023-09-12 08:38:14 [scrapy-playwright] INFO: Browser chromium launched
> 
> 2023-09-12 08:38:14 [scrapy-playwright] DEBUG: Browser context started: 'dc2d0bfd-5160-11ee-ba69-94c6911285da' (persistent=False, remote=False)
> 
> 2023-09-12 08:38:15 [scrapy-playwright] DEBUG: [Context=dc2d0bfd-5160-11ee-ba69-94c6911285da] New page created, page count is 1 (1 for all contexts)
> 
> 2023-09-12 08:38:15 [scrapy-playwright] DEBUG: [Context=dc2d0bfd-5160-11ee-ba69-94c6911285da] Request: <GET https://httpbin.org/delay/10> (resource type: document)
> 
> 2023-09-12 08:38:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://httpbin.org/delay/10>
> 
> Traceback (most recent call last):
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
> 
>     result = context.run(
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
> 
>     return g.throw(self.type, self.value, self.tb)
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 54, in process_request
> 
>     return (yield download_func(request=request, spider=spider))
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/twisted/internet/defer.py", line 1065, in adapt
> 
>     extracted = result.result()
> 
>   File "/scrapy-playwright/scrapy_playwright/handler.py", line 322, in _download_request
> 
>     result = await self._download_request_with_page(request, page, spider)
> 
>   File "/scrapy-playwright/scrapy_playwright/handler.py", line 357, in _download_request_with_page
> 
>     response = await page.goto(url=request.url, **page_goto_kwargs)
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9251, in goto
> 
>     await self._impl_obj.goto(
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_page.py", line 479, in goto
> 
>     return await self._main_frame.goto(**locals_to_params(locals()))
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 147, in goto
> 
>     await self._channel.send("goto", locals_to_params(locals()))
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
> 
>     return await self._connection.wrap_api_call(
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
> 
>     return await cb()
> 
>   File "/scrapy-playwright/venv-scrapy-playwright/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
> 
>     result = next(iter(done)).result()
> 
> playwright._impl._api_types.TimeoutError: Timeout 100ms exceeded.
> 
> =========================== logs ===========================
> 
> navigating to "https://httpbin.org/delay/10", waiting until "commit"
> 
> ============================================================
> 
> 2023-09-12 08:38:15 [scrapy.core.engine] INFO: Closing spider (finished)
> 
> ```
> 
> 
> 
> The keyword argument is being used correctly in the `Page.goto` call. Notice that if you pass an incorrect argument name you get:
> 
> ```
> 
> TypeError: Page.goto() got an unexpected keyword argument 'incorrect_key'
> 
> ```
> 
> and if you pass an incorrect value for `wait_until` you get:
> 
> ```
> 
> playwright._impl._api_types.Error: wait_until: expected one of (load|domcontentloaded|networkidle|commit)
> 
> ```

I suspect it might be a version issue. We are using version 0.0.5. Could it be that the "wait_until" parameter hasn't been enabled yet?

**Comment by elacuesta** [comment]
The `playwright_page_goto_kwargs` request meta key was added in [0.0.19](https://github.com/scrapy-plugins/scrapy-playwright/blob/main/docs/changelog.md#v0019-2022-07-17).

**Comment by LoyAngel** [comment]
> The `playwright_page_goto_kwargs` request meta key was added in [0.0.19](https://github.com/scrapy-plugins/scrapy-playwright/blob/main/docs/changelog.md#v0019-2022-07-17).

OK, we're figuring upadting the version next. 
Really grateful for your help ,bro !
