### ISSUE TITLE
About memory leak

### ISSUE THREAD

**Issue by Harvi-C** [scrapy-plugins/scrapy-playwright#240]
`
      yield scrapy.Request(url=ALL_IMAGE_URL + str(page), callback=self.parse, meta=dict(
          playwright=True,
          playwright_page_methods=[
              PageMethod("evaluate", "window.scrollBy(0, 500)"),
              PageMethod("wait_for_timeout", timeout),
          ]
`

I use the simplest boot method in scrapy, the memory footprint of the machine gets higher and higher, after I crawl about 700 pages, the memory footprint of the machine increased from 4-5GB at the beginning to 18GB, I don't know why

I didn't turn on "playwright_include_page=True", and i set "PLAYWRIGHT_MAX_PAGES_PER_CONTEXT = 16"

So is this a memory leak ? and what do I do about it
 
<img width="1555" alt="image" src="https://github.com/scrapy-plugins/scrapy-playwright/assets/45502978/cb47ca41-f8c6-4c0a-b3bd-36a8501c45d7">

**Comment by Harvi-C** [comment]
I didn't turn on "playwright_include_page=True", 

So do I need to explicitly call page.close() or page.context.close(), how do I get the page ?

**Comment by Harvi-C** [comment]
I noticed the problem: https://github.com/microsoft/playwright/issues/6319

**Comment by elacuesta** [comment]
Should this be closed then?

**Comment by mikewronski** [comment]
@Harvi-C do you have a solution to this problem? I am also encountering boundless memory in scrapy and playwright, using a single context for all pages and not turning on playwright_include_page=True
