### ISSUE TITLE
how to use playwright with SitemapSpider

### ISSUE THREAD

**Issue by zaheerkzz** [scrapy-plugins/scrapy-playwright#249]
Im using sitemap to get urls for scrapping and with playwright i have issue integrating:

`for entry in entries:
      for substr in testing_urls:
          if substr in entry["loc"]:
              yield scrapy.Request(substr, callback=self.parse_item, meta={"playwright": True})`

giving me following error:
`    yield d["loc"]
TypeError: 'Request' object is not subscriptable`

**Comment by elacuesta** [comment]
I guess your `d` object is a `Request` but you're treating it as a `dict`; hard to know without more context. Closing, this looks like a general Python question, not specific to this package.
