### ISSUE TITLE
Modifying headers when sending out the request

### ISSUE THREAD

**Issue by louislsh68** [scrapy-plugins/scrapy-playwright#258]
I am using scrapy-playwright with brave. I find out that the code with add "pragma" and "cache-control" as an header. Is it possible to remove it? Usually, we should use route function. But route is being used in the base code of scrapy-playwright

**Comment by louislsh68** [comment]
Tried it is the same. I also read something funny in pupeteer user on chromium, They also faced the same issue
https://github.com/puppeteer/puppeteer/issues/3403
Not sure if this is the same issue across automation control via Chromium

My code for ref
`#Brave-For discussion
import scrapy,random
from scrapy.exceptions import CloseSpider
from http.cookies import SimpleCookie
from playwright import async_api


max_spider_run_time = 1200

class MySpider(scrapy.Spider):
    name = 'Scraper'
    
    def should_abort_request(request):
        return (
            request.resource_type in ["image", "images", "font", "stylesheet", "media"]
            )

    def get_custom_headers(browser_type: str, playwright_request: async_api.Request, scrapy_headers: scrapy.http.headers.Headers) -> dict:
        return {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", 
            "Accept-Encoding": "gzip, deflate", 
            "Accept-Language": "en-GB", 
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        }

    custom_settings = {
        'PLAYWRIGHT_BROWSER_TYPE':'chromium',
        'DOWNLOAD_DELAY': 4.0,
        'PLAYWRIGHT_LAUNCH_OPTIONS': {
            'headless': False,
            "slow_mo": 20000,
            "timeout": 30000,
            "executable_path": "/Applications/Brave Browser.app/contents/MacOS/Brave Browser",
            "args": [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--no-first-run',
                '--disable-blink-features=AutomationControlled'],
        },
        "PLAYWRIGHT_ABORT_REQUEST" : should_abort_request,
        "PLAYWRIGHT_PROCESS_REQUEST_HEADERS": get_custom_headers,
    }

    def __init__(self, *args, **kwargs):
        super(MySpider, self).__init__(*args, **kwargs)

    async def closed(self, reason):
        if hasattr(self, 'playwright_context') and self.playwright_context is not None:
            await self.playwright_context.close()
            self.playwright_context = None

        if reason == 'closespider_timeout':
            self.log("Spider run time exceeded")
    
    def start_requests(self):
        self.current_country_index = 0
        yield from self.go_to_website()

    def go_to_website(self, offset=0):
        if self.current_country_index < len(self.countryabbr_list):
            countryabbr = self.countryabbr_list[self.current_country_index]
            rand_port = random.randint(10000, 20000)
            first_two_chars = countryabbr[:2]
            init_request = scrapy.Request(
                url = "https://httpbin.org/headers",
                callback=self.retrieve_cookies,
                errback=self.handle_error,
                dont_filter=True,  
                meta={
                    'playwright': True, 
                    'dont_merge_cookies': True,
                    'offset': offset,
                    'playwright_context': f'{first_two_chars}_{rand_port}',
                },
            )
            yield init_request
        else:
            raise CloseSpider('No more things to scrape')

    def retrieve_cookies(self, response):
        raw_cookies = response.headers.getlist('Set-Cookie')
        self.cookies = {}
        for rc in raw_cookies:
            cookie = SimpleCookie(rc.decode())
            for key, morsel in cookie.items():
                self.cookies[key] = morsel.value
        self.headers = response.request.headers`

The headers received
![5DF50325-991E-4C9C-A148-D5F8298FDF4A](https://github.com/scrapy-plugins/scrapy-playwright/assets/148164382/14078347-124c-460c-9511-b41a2531182d)

**Comment by elacuesta** [comment]
I see. This might be an upstream issue with Playwright and/or the underlying browser. Please try to reproduce using standalone Playwright as indicated in https://github.com/scrapy-plugins/scrapy-playwright#reporting-issues. If the issue also appears that way, it's not caused by this package.

**Comment by elacuesta** [comment]
This also happens with standalone Playwright, which means it's not caused by this package. If you think there is an issue with this behavior I'd recommend you to open an issue upstream in [playwright-python](https://github.com/microsoft/playwright-python).

```
$ playwright --version
Version 1.44.0
```

Playwright script:
```python
# headers.py
import asyncio
from playwright.async_api import async_playwright

async def handle(route, request):
    """Adapted from https://playwright.dev/python/docs/api/class-route#route-continue"""
    headers = {"foo": "foo-value", "pragma": None, "cache-control": None}
    await route.continue_(headers=headers)

async def main():
    async with async_playwright() as pw:
        for browser_type in (pw.chromium, pw.firefox):
            print(f"Browser type: {browser_type.name}")
            browser = await browser_type.launch()
            page = await browser.new_page()
            await page.route("**", handle)
            await page.goto("https://httpbin.org/headers")
            print(await page.content())
            await page.screenshot(path=f"headers_{browser_type.name}.png", full_page=True)
            await browser.close()

asyncio.run(main())
```

```
$ python headers.py
Browser type: chromium
<html><head><meta name="color-scheme" content="light dark"><meta charset="utf-8"></head><body><pre>{
  "headers": {
    "Accept-Encoding": "gzip, deflate, br", 
    "Cache-Control": "no-cache", 
    "Foo": "foo-value", 
    "Host": "httpbin.org", 
    "Pragma": "no-cache", 
    "Priority": "u=0, i", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/125.0.6422.26 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-668f4ce8-4d39c5126db1ccc41300f02e"
  }
}
</pre><div class="json-formatter-container"></div></body></html>

Browser type: firefox
<html><head><link rel="stylesheet" href="resource://content-accessible/plaintext.css"></head><body><pre>{
  "headers": {
    "Cache-Control": "no-cache", 
    "Foo": "foo-value", 
    "Host": "httpbin.org", 
    "Pragma": "no-cache", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "X-Amzn-Trace-Id": "Root=1-668f4ce9-223475ee39e00aef656d6300"
  }
}
</pre></body></html>
```
