### ISSUE TITLE
Unable to save downloaded file

### ISSUE THREAD

**Issue by sanjeethboddi** [scrapy-plugins/scrapy-playwright#259]
```
yield scrapy.Request(
      url,
      meta={
      'playwright': True,
      'playwright_include_page': True, 
      'playwright_page_methods':[
          ...
          PageMethod("click", selector='#export > ul > li > button'), # downloads csv file
          ...
                              
          ],
          
      'errback': self.errback,
      })
   ```
   This page method downloads the file but it's not accessible. I want to save the downloaded file even after the program terminates.

**Comment by elacuesta** [comment]
I assume the click triggers a [download](https://playwright.dev/python/docs/downloads), please try handling the `download` event with [`playwright_page_event_handlers`](https://github.com/scrapy-plugins/scrapy-playwright#handling-page-events)

**Comment by sanjeethboddi** [comment]
Got it 👍
