### ISSUE TITLE
How to disable file download?

### ISSUE THREAD

**Issue by NiuBlibing** [scrapy-plugins/scrapy-playwright#261]
Hi, I'm using scarpy-playwight to do common crawling which some url maybe a very large file download link.The files is auto download to path like `/tmp/playwright-artifacts-p5tOHg/310a6a9c-c2cb-4b29-8a42-fe7c6f0de8ec` and consumes a lot of disk IO and bandwidth. Is there a way to disable it?

**Comment by elacuesta** [comment]
Have you checked [`PLAYWRIGHT_ABORT_REQUEST`](https://github.com/scrapy-plugins/scrapy-playwright#playwright_abort_request)?

**Comment by elacuesta** [comment]
Another possibility might be to handle the `download` event with [`playwright_page_event_handlers`](https://github.com/scrapy-plugins/scrapy-playwright#playwright_page_event_handlers) and [cancel](https://playwright.dev/python/docs/api/class-download#download-cancel) it.

**Comment by NiuBlibing** [comment]
Thanks, [playwright_page_event_handlers](https://github.com/scrapy-plugins/scrapy-playwright#playwright_page_event_handlers) works for me.
