### ISSUE TITLE
Activating chromium_sandbox in PLAYWRIGHT_LAUNCH_OPTIONS

### ISSUE THREAD

**Issue by jkobti** [scrapy-plugins/scrapy-playwright#273]
Hello,

I tried to activate the `chromium_sandbox` by adding `"chromium_sandbox": True` to the `PLAYWRIGHT_LAUNCH_OPTIONS`, also obviously I am using chromium browser. However, I didn't see any related logs that could confirm whether the browser was launched with sandbox.

Could you please clarify if what I have done is sufficient? If not, could you guide me on the correct way to do this?

**Comment by elacuesta** [comment]
As [the docs](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#playwright_launch_options) say, values for PLAYWRIGHT_LAUNCH_OPTIONS are passed to [BrowserType.launch](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch). The [chromium_sandbox](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-chromium-sandbox) argument is listed there so I'd say that should be enough. This plugin doesn't rely all logs from Playwright, that's probably why there is no specific message about this option.
