### ISSUE TITLE
scrapy-playwright connect to remote firefox instance

### ISSUE THREAD

**Issue by Ehsan-U** [scrapy-plugins/scrapy-playwright#277]
Currently, **scrapy-playwright** only supports Chromium for connecting to remote browser instances over CDP (Chrome DevTools Protocol). Firefox is quite effective in bypassing detections against some anti-bot measures. Is there any possibility to add support for connecting to remote Firefox instances? I understand that it's not possible over CDP, but Playwright provides a **connect()** method which allows connecting to remote Firefox instance. I have tried it with [browserless](https://github.com/browserless/browserless) platform, its working fine but scrapy-playwright only support **connect_over_cdp()** method at the moment.

**Comment by elacuesta** [comment]
Sounds like a good feature to have, thanks for the request.

**Comment by elacuesta** [comment]
Released as [v0.0.38](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.38). See the [PLAYWRIGHT_CONNECT_URL](https://github.com/scrapy-plugins/scrapy-playwright/tree/v0.0.38?tab=readme-ov-file#playwright_connect_url) and [PLAYWRIGHT_CONNECT_KWARGS](https://github.com/scrapy-plugins/scrapy-playwright/tree/v0.0.38?tab=readme-ov-file#playwright_connect_kwargs) settings.
