### ISSUE TITLE
Windows WSL scrapy-playwright chromium headful mode not working

### ISSUE THREAD

**Issue by gelodefaultbrain** [scrapy-plugins/scrapy-playwright#278]
Hi!

Apologies if I am not writing this correctly. But I just wanted to raise this issue. I am currently running a scrapy spider on my Windows machine, particularly in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). When I run the program I am getting this. Please see image attached.

![image](https://github.com/scrapy-plugins/scrapy-playwright/assets/55988471/9c922fcf-1f18-4fec-ad3f-d298a02f2b0a)

As you can see, it's just like that. We can see the browser (chromium) exists by looking at the sides of it but at the middle it's completely blank. Like you can see through it. Weird thing is the spider runs successfully and I am able to scrape the data I want accordingly. May I ask what could be the solution for this? Do we need to install something that is a dependency requirement?

**Additional Information:**
Just wanted to add that I tried switching to "firefox" and it worked well. I can clearly see what is happening. I tried it with "webkit" as well but it's the opposite of "chromium" , the middle part is completely white. But using all the browsers I am able to scrape the data gracefully.

My custom settings:
```
    custom_settings = {
        "PLAYWRIGHT_LAUNCH_OPTIONS": {
            "headless": False,
            "slow_mo": 9000,
        },
    }
```

Thank you!

**Comment by elacuesta** [comment]
Found https://github.com/microsoft/playwright/issues/21813#issuecomment-1476754006 via https://stackoverflow.com/a/78320155.
In short, looks like you could solve it by disabling GPU support in WSL.

**Comment by krukonshedul** [comment]
> Found [microsoft/playwright#21813 (comment)](https://github.com/microsoft/playwright/issues/21813#issuecomment-1476754006) via https://stackoverflow.com/a/78320155. In short, looks like you could solve it by disabling GPU support in WSL.

The solution there was what made it working for me

**Comment by gelodefaultbrain** [comment]
Hi sorry for the late reply YES!! disabling GPU support made it work.  It can be done via GUI by just disabling this by the way.

![DeepinScreenshot_select-area_20240703092745](https://github.com/scrapy-plugins/scrapy-playwright/assets/55988471/5b632913-3eb8-4627-8269-18b79162ebc2)

Thanks all for the help! Closing this now as solved!
