### ISSUE TITLE
Task exception was never retrieved error

### ISSUE THREAD

**Issue by jessrosenfield** [scrapy-plugins/scrapy-playwright#3]
The scraper's ability to output items seems unaffected, but at the end of the playwright request's response callback I get the following.

```
2021-01-26 11:58:58 machinename asyncio[21762] ERROR Task exception was never retrieved
future: <Task finished coro=<Route.continue_() done, defined at /Users/jessica/.local/share/virtualenvs/upwork-scrapers-2AkzeUYG/lib/python3.7/site-packages/playwright/async_api.py:481> exception=Error('Target page, context or browser has been closed')>
Traceback (most recent call last):
  File "/Users/jessica/.local/share/virtualenvs/upwork-scrapers-2AkzeUYG/lib/python3.7/site-packages/playwright/async_api.py", line 508, in continue_
    postData=postData,
  File "/Users/jessica/.local/share/virtualenvs/upwork-scrapers-2AkzeUYG/lib/python3.7/site-packages/playwright/_network.py", line 195, in continue_
    await self._channel.send("continue", cast(Any, overrides))
  File "/Users/jessica/.local/share/virtualenvs/upwork-scrapers-2AkzeUYG/lib/python3.7/site-packages/playwright/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/Users/jessica/.local/share/virtualenvs/upwork-scrapers-2AkzeUYG/lib/python3.7/site-packages/playwright/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._types.Error: Target page, context or browser has been closed
```

**Comment by althayr** [comment]
Hi @jessrosenfield, i saw similar bugs when using the library.

One issue that i noticed is that the library is propagating Google Chrome errors, for example when visiting http://httpbin.org/status/404 scrapy throws a exception.

![Screenshot from 2021-01-26 18-51-39](https://user-images.githubusercontent.com/27309678/105910540-ddf83180-6007-11eb-89eb-19d1bae65fd6.png)

If the page you visit has other requests pending response when something similar happens, it can be the case that this propagates errors on other places (asyncio, playwright)

**Comment by elacuesta** [comment]
Hi, could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by jessrosenfield** [comment]
Whoops I'm the worst kind of user!! I unfortunately ended up scrapping my use of scrapy-playwright for that scraper since playwright ended up not being necessary.

I'll be using the package again and will provide necessary info if I come across a similar issue 😅 in the meantime, at least other users know they're not the only one if they come across this. @althayr's suggestion that I may be closing the page with incomplete pending events seems like a plausible root cause.

**Comment by iemelyanenkova** [comment]
I have similar issue:
`Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at C:\Users\iemelyanenkova\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_wait_helper.py:85> exception=CancelledError()>
concurrent.futures._base.CancelledError
Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at C:\Users\iemelyanenkova\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_wait_helper.py:85> exception=CancelledError()>
concurrent.futures._base.CancelledError
Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at C:\Users\iemelyanenkova\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_wait_helper.py:85> exception=CancelledError()>
concurrent.futures._base.CancelledError
Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at C:\Users\iemelyanenkova\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_wait_helper.py:85> exception=CancelledError()>
concurrent.futures._base.CancelledError

Process finished with exit code 0
`

My test:
`from playwright.sync_api import sync_playwright


EMAIL = "exemple@example.com"
PASSWORD = "example"


def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    # Open new page
    page = context.new_page()

    # Go to my_fisrt_url/
    page.goto("my_fisrt_url/", wait_until='networkidle')

    # Verify redirect to login page
    try:
        page.expect_navigation(url="my_fisrt_url/login")
    except Exception as error:
        page.screenshot(path="screenshot.png", full_page=True)

    # Actions on my_fisrt_url/login
    # Click [placeholder="Username/Email"]
    page.click("[placeholder=\"Username/Email\"]")
    # Fill [placeholder="Username/Email"]
    page.fill("[placeholder=\"Username/Email\"]", EMAIL)
    # Click text=Continue
    page.click("text=Continue")

    # Verifying page loading
    page.wait_for_url(url="my_second_url/login")
    try:
        page.wait_for_url(url="my_second_url/login", wait_until='networkidle')
    except Exception as error:
        f"Page can't be loaded: {page.url}"

    print("Test end")

    # ---------------------
    context.close()
    browser.close()
    playwright.stop()

with sync_playwright() as playwright:
    run(playwright)
`

Test response:
`first_script.py
Test end
Future exception was never retrieved
future: <Future finished exception=Error('Target page, context or browser has been closed')>
playwright._impl._api_types.Error: Target page, context or browser has been closed

Process finished with exit code 0`

I couldn't find a way to handle it. Could someone help?

**Comment by Gallaecio** [comment]
Closing due to lack of feedback.
