### ISSUE TITLE
expect(locator) not supported?

### ISSUE THREAD

**Issue by crimsonduelist** [scrapy-plugins/scrapy-playwright#301]
I m trying to use the (locator.1)or_(locator) like in the example here
https://playwright.dev/python/docs/api/class-locator#locator-or i.e. with Locator Assertions https://playwright.dev/python/docs/api/class-locatorassertions
but name 'expect' is not defined ??

**Comment by elacuesta** [comment]
Have you imported it? From [the link you shared](https://playwright.dev/python/docs/api/class-locatorassertions):
```python
from playwright.async_api import Page, expect
```

**Comment by crimsonduelist** [comment]
> Have you imported it? From [the link you shared](https://playwright.dev/python/docs/api/class-locatorassertions):
> 
> ```python
> from playwright.async_api import Page, expect
> ```

f, duh, thanks
intellisense in vscode wasnt seeing it - It was seeing Expect
