### ISSUE TITLE
Question: Intercepting JS and CSS reponses

### ISSUE THREAD

**Issue by ivanvza** [scrapy-plugins/scrapy-playwright#315]
In the `handler.py` it uses the `page.on("response", _make_response_logger(context_name, spider))` to log the url and response of which the browser receives, but without the body content (due to the await)

is there a similar method I can implement to catch/see the body of that response within my scraper, without the need to make additional requests?

**Comment by elacuesta** [comment]
You're probably looking for [`playwright_page_event_handlers`](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#playwright_page_event_handlers).
