### ISSUE TITLE
Scrapy-playwright not sending a Content-Type: application/x-www-form-urlencoded when just Playwright does

### ISSUE THREAD

**Issue by DaveB93** [scrapy-plugins/scrapy-playwright#329]
when running the code with just playwright it 'works'  (with the right login )  with the wrong login it still gives an appropriate error. 
when running with scrapy-playwright it gets a 400 error. 

looking at a diff of the requests it seems like when I'm navigating to submit a form via playwright that the content type isn't being sent correctly.   It's entirely possibly this isn't the right way to to do it though ? 

[scrapy-playwright.zip](https://github.com/user-attachments/files/17788240/scrapy-playwright.zip)

(.venv) PS C:\Users\User\Documents\code\bcmea_playwright> scrapy version -v
Scrapy       : 2.11.2
lxml         : 5.3.0.0
libxml2      : 2.11.7
cssselect    : 1.2.0
parsel       : 1.9.1
w3lib        : 2.2.1
Twisted      : 24.10.0
Python       : 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
pyOpenSSL    : 24.2.1 (OpenSSL 3.3.2 3 Sep 2024)
cryptography : 43.0.3
Platform     : Windows-10-10.0.22631-SP0
(.venv) PS C:\Users\User\Documents\code\bcmea_playwright> playwright --version
Version 1.48.0
(.venv) PS C:\Users\User\Documents\code\bcmea_playwright> python -c "import scrapy_playwright; print(scrapy_playwright.__version__)"
0.0.42
(.venv) PS C:\Users\User\Documents\code\bcmea_playwright>

**Comment by DaveB93** [comment]
adding PLAYWRIGHT_PROCESS_REQUEST_HEADERS=None to scrapy-playwright does fix this though.

**Comment by elacuesta** [comment]
> adding PLAYWRIGHT_PROCESS_REQUEST_HEADERS=None to scrapy-playwright does fix this though.

Correct, this is expected behavior. Closing.
