### ISSUE TITLE
Respect Scrapy extensions

### ISSUE THREAD

**Issue by scrapenetwork** [scrapy-plugins/scrapy-playwright#40]
Hello,

this script use to respect scrapy memory_usage
Now it no longer does…

it does not do anything when enabled now

**Comment by elacuesta** [comment]
Could you please elaborate? The scrapy-playwright download handler does not interact directly with the `MemoryUsage` extension.

**Comment by scrapenetwork** [comment]
Correct

before it didnt interact with extension but respects them meaning , for this extension it would close-shut-down, now it does not , it does nothing .

ive tried both the settings py and in custom settings route and both fail. I also tried setting the value low (50) and it did pull up the scrapy log extension info but did not respect the extension as well. Any tips / help would be great thxs

**Comment by elacuesta** [comment]
Thanks for the follow up. Unfortunately, I still don't understand exactly what is the issue, nor can I reproduce with the available information. Please, provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by scrapenetwork** [comment]
import hashlib
import logging
from pathlib import Path
from typing import Generator, Optional

from scrapy import Spider
from scrapy.crawler import CrawlerProcess
from scrapy.http.response import Response


class BooksSpider(Spider):
    """Extract all books, save screenshots."""

    name = "books"
    start_urls = ["http://books.toscrape.com"]

    def parse(self, response: Response, current_page: Optional[int] = None) -> Generator:
        page_count = response.css(".pager .current::text").re_first(r"Page \d+ of (\d+)")
        page_count = int(page_count)
        for page in range(2, page_count + 1):
            yield response.follow(f"/catalogue/page-{page}.html", cb_kwargs={"current_page": page})

        current_page = current_page or 1
        for book in response.css("article.product_pod a"):
            yield response.follow(
                book,
                callback=self.parse_book,
                meta={
                    "playwright": True,
                    "playwright_include_page": True,
                    "playwright_context": f"page-{current_page}",
                },
            )

    async def parse_book(self, response: Response) -> dict:
        url_sha256 = hashlib.sha256(response.url.encode("utf-8")).hexdigest()
        page = response.meta["playwright_page"]
        await page.screenshot(
            path=Path(__file__).parent / "books" / f"{url_sha256}.png", full_page=True
        )
        await page.close()
        return {
            "url": response.url,
            "title": response.css("h1::text").get(),
            "price": response.css("p.price_color::text").get(),
            "breadcrumbs": response.css(".breadcrumb a::text").getall(),
            "image": f"books/{url_sha256}.png",
        }


if __name__ == "__main__":
    process = CrawlerProcess(
        settings={
            "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
            "DOWNLOAD_HANDLERS": {
                # "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
                "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            },
            "LOG_ENABLED":True,
            "LOG_LEVEL":"DEBUG",
            "MEMUSAGE_ENABLED":True,
            "MEMUSAGE_LIMIT_MB":50,
            "CONCURRENT_REQUESTS": 32,
            "CLOSESPIDER_ITEMCOUNT": 100,
            "FEEDS": {
                "books.json": {"format": "json", "encoding": "utf-8", "indent": 4},
            },
        }
    )
    process.crawl(BooksSpider)
    logging.getLogger("scrapy.core.engine").setLevel(logging.WARNING)
    logging.getLogger("scrapy.core.scraper").setLevel(logging.WARNING)
    process.start()
    

2021-12-08 09:13:04 [scrapy.extensions.logstats] INFO: Crawled 50 pages (at 50 pages/min), scraped 0 items (at 0 items/min)
2021-12-08 09:13:04 [scrapy.extensions.memusage] ERROR: Memory usage exceeded 50M. Shutting down Scrapy...
2021-12-08 09:13:05 [scrapy-playwright] DEBUG: Browser context started: 'page-1'
2021-12-08 09:13:10 [scrapy-playwright] DEBUG: Browser context started: 'page-7'
    
 

The plugin never respects the scrapy extension..does nothing it just continues
Other older v. did respect it 
Maybe i am doing something wrong

**Comment by elacuesta** [comment]
Taking a closer look, I believe the memory used by `playwright` is not actually taken into account by the `MemUsage` extension. The extension calls `resource.getrusage(resource.RUSAGE_SELF)` [here](https://github.com/scrapy/scrapy/blob/2.5.1/scrapy/extensions/memusage.py#L48), which means it will only consider the memory of the current process ([docs](https://docs.python.org/3/library/resource.html#resource.getrusage)). However, `playwright` runs as a separate process.

**Comment by scrapenetwork** [comment]
Have been trying to fix this with no success.
Which is strange older versions would handle this

**Comment by elacuesta** [comment]
Closing, there's nothing to do on this package's side. Please create an issue in Scrapy if you think this is a problem.

**Comment by scrapenetwork** [comment]
Scrapy does its job in the log its scrapy that closes perfectly fine.

its the plugin that does not respect it, if you add the extension with scrapy works just fine, the moment you add this plugin along with the extension , the extension is not respected by the plugin.

all is well, i will continue to find a solution
