### ISSUE TITLE
 ProactorEventLoop is not supported, got

### ISSUE THREAD

**Issue by Novanesthi** [scrapy-plugins/scrapy-playwright#41]
i get this error , i use basic usages, [ "ProactorEventLoop is not supported, got: <ProactorEventLoop running=False closed=False debug=False>" ]

Can you help me

**Comment by elacuesta** [comment]
Are you using Windows? If so, this is probably the same as #7.

**Comment by Novanesthi** [comment]
> Apakah Anda menggunakan Windows? Jika demikian, ini mungkin sama dengan #7 .

so this is some kind of bugs, for windows? sorry I'm still a beginner in programming, so I'm quite confused by this error

**Comment by elacuesta** [comment]
This package does not currently work out-of-the-box on Windows, for the reasons mentioned [here](https://github.com/scrapy-plugins/scrapy-playwright/issues/7#issuecomment-808824121). It seems like it's possible to make it run on top of [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), but I haven't personally made any attempts at that.
