### ISSUE TITLE
lazy load

### ISSUE THREAD

**Issue by Novanesthi** [scrapy-plugins/scrapy-playwright#43]
i use , playwright + bs4 , to scrape the web with lazy loading , using mouse.wheel and time sleep its work to scrape contents , how to use in playwright scrapy plugin? "mouse.wheel" , i use page coroutine still not working , to display content i need 40seconds for engine to parse it

**Comment by elacuesta** [comment]
`PageCoroutine("wait_for_timeout", 40 * 1000)` might work in your case.
