### ISSUE TITLE
can't set PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT to 0

### ISSUE THREAD

**Issue by JustinQHu** [scrapy-plugins/scrapy-playwright#47]
BY default, playwright has a timeout of 30 seconds for a lot of its behaviors, including: 
![image](https://user-images.githubusercontent.com/16525943/148618826-e8db7b96-afbb-486b-b8a3-b498a433aa50.png)

You can set 0 to disable timeout for these actions in playwright,  referring to [Playwright API reference](https://playwright.dev/python/docs/next/api/class-page#page-set-default-timeout
)

Current code(line 68, scrape_playwright/hander.py) doesn't work when the value is 0:
`self.default_navigation_timeout: Optional[int] = (
            crawler.settings.getint("PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT") or None
        )`

As you can see, then PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT is 0, the value of this expression is still None, for 

> 0 or None

  is still None in Python.

Rightnow, I  just subclass ScrapyPlaywrightDownloadHandler to work around this issue. 

Thank you.

**Comment by elacuesta** [comment]
You are correct, thanks for pointing it out.

**Comment by elacuesta** [comment]
Fixed in 6875f7cdc03fa912451fbe3ba96b7a7c9c503588, released as [`v0.0.8`](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.8). Thanks again for the report.
