### ISSUE TITLE
Limiting number of open pages

### ISSUE THREAD

**Issue by SamGalanakis** [scrapy-plugins/scrapy-playwright#59]
I am running a scraper that opens a new page in playwright for certain types of links and would like to throttle these requests by say setting a max number of pages than can be open at any one time and adding them to a queue. How should I go about that? Currently it seems to open too many instances and overwhelms the cpu. Thanks in advance.

**Comment by samwillis** [comment]
See: https://github.com/scrapy-plugins/scrapy-playwright/issues/6

I'm having success with the branch from that issue.

**Comment by elacuesta** [comment]
Closing as duplicate of #6
