### ISSUE TITLE
Set option to have maximum number of pages in context

### ISSUE THREAD

**Issue by lucasnobre212** [scrapy-plugins/scrapy-playwright#6]
I am having a problem where the spider is creating a lot of pages and it is causing memory issues. It would be nice if we could control the maximum amount of pages before sending a new _download_request to create a new one. This happens a lot when I start using the page from 'playwright-page' in a parse method, because it will bypass Scrapy request workflow. Can this be done using signals?

**Comment by elacuesta** [comment]
I think this is a valid concern, I will look into a way of dealing with it. In the meantime, have you tried limiting your [`CONCURRENT_REQUESTS`](https://docs.scrapy.org/en/2.4/topics/settings.html#concurrent-requests)?

**Comment by lucasnobre212** [comment]
Yes, but if I send the page with 'playwright-page' argument, it will remain opened. When this happens, scrapy think that there is an available room for another request and opens another page. This keeps happening until the computer freezes.

**Comment by samwillis** [comment]
Hi, so I'm fairly new to Scrapy and Playwright so forgive me if I'm wrong on this.

I have been using your [max-pages-per-context](https://github.com/scrapy-plugins/scrapy-playwright/tree/max-pages-per-context) branch (thanks!) and think I may have spotted a bug, it's more visible in this branch as it blocks up all "tabs" eventually but I think I might be present in the main branch.

When using `"playwright_include_page": True` to get the playwright page instance in your parse method, if the page doesn't exist (error 404) it gets stuck open, using up one of the available slots. Eventually, this results in all slots getting used by 404 pages. As far as I can tell the callback parse method isn't called so I can't close the 404ed page from there.

If I get some time I will dig into the code and try and find the problem, but a workaround I'm using is to do a simple HEAD request first (without playwright) to check if the page exists before opening with playwright.

**Comment by samwillis** [comment]
I said I was new to it. So I worked out you need to have an `errback` when using `playwright_include_page`, then do something like:

```
async def error_cb(self, failure):
    page = failure.request.meta["playwright_page"]
    await page.close()
```

May be worth documenting that needs to be done to handle error page closing when using `playwright_include_page`.

**Comment by elacuesta** [comment]
Great catch @samwillis, thanks. I've added it to #16.
