### ISSUE TITLE
Grabbing parameters from default requests

### ISSUE THREAD

**Issue by lime-n** [scrapy-plugins/scrapy-playwright#61]
`scrapy_playwright` tries to imitate the web-browser so it downloads all resources (images, scripts, stylesheets, etc). Therefore, given this information is downloaded, is it possible to grab the payload from specific requests sent from the network tab - specifically from the fetch/XHR tab?

For example (minimal reproducible code):
```
import scrapy
from scrapy_playwright.page import PageCoroutine

class testSpider(scrapy.Spider):
    name = 'test'

    def start_requests(self):
        yield scrapy.Request(
            url="http://quotes.toscrape.com/scroll",
            cookies={"foo": "bar", "asdf": "qwerty"},
            meta={
                "playwright": True,
                "playwright_page_coroutines": [
                    PageCoroutine("wait_for_selector", "div.quote"),
                    PageCoroutine("evaluate", "window.scrollBy(0, document.body.scrollHeight)"),
                    PageCoroutine("wait_for_selector", "div.quote:nth-child(11)"),  # 10 per page
                    PageCoroutine( "screenshot", path="scroll.png", full_page=True
                    ),
                ],
            },
        )
    def parse(self, response):
        pass
```

Produces the following output:

```
2022-02-21 11:50:39 [scrapy-playwright] DEBUG: [Context=default] Request: <GET http://quotes.toscrape.com/api/quotes?page=2> (resource type: xhr, referrer: http://quotes.toscrape.com/scroll)
2022-02-21 11:50:39 [scrapy-playwright] DEBUG: [Context=default] Request: <GET http://quotes.toscrape.com/api/quotes?page=3> (resource type: xhr, referrer: http://quotes.toscrape.com/scroll)
2022-02-21 11:50:39 [scrapy-playwright] DEBUG: [Context=default] Request: <GET http://quotes.toscrape.com/api/quotes?page=4> (resource type: xhr, referrer: http://quotes.toscrape.com/scroll)
...
```

Very similar to firefox which allows you to copy the url and url parameters. The aim is to store the url parameters into a list each time playwright downloads a specific request url. With a more complex website I would have to find specific requests urls and grab the url parameters. 

Something like:

```
if response.meta['resource_type'] is 'xhr':
    print(parameters(response.meta['resource_type_urls'])) 
```

This is a pseduo-example to express what I want to get; `parameters` would be a function to grab the url parameters.

Or perhaps it works like this:
```
if response.meta['resource_type'] is 'xhr':
    print(response.meta['parameters']) 
```

However saving it into `response.meta` will likely overload the results if I have a large number of urls for resource types, and url parameters are fairly large dicts.

 - I'm convinced this data is available as it's downloaded however I just do not know how to get it.

**Comment by lime-n** [comment]
For additional information, we have the following output from above - 

```
 'playwright/context_count': 1,
 'playwright/page_count': 1,
 'playwright/page_count/closed': 1,
 'playwright/request_count': 15,
 'playwright/request_count/method/GET': 15,
 'playwright/request_count/navigation': 1,
 'playwright/request_count/resource_type/document': 1,
 'playwright/request_count/resource_type/font': 1,
 'playwright/request_count/resource_type/script': 1,
 'playwright/request_count/resource_type/stylesheet': 3,
 'playwright/request_count/resource_type/xhr': 9,
```
The output counts the `resource_type`, however I want to store or yield the specific resource types and their url parameters that are sent to the requests to imitate the web-browser.

How do I access these? I have tried looking at the source code but I'm stilling trying to grasp the marvel of it.

**Comment by elacuesta** [comment]
If I understand correctly, you should be able to get the info you want by attaching a [page event handler](https://github.com/scrapy-plugins/scrapy-playwright#page-events) for the [`request`](https://playwright.dev/docs/api/class-page#page-event-request) event. Note that the links in the readme seem to be broken, I'll try to update them soon.

**Comment by lime-n** [comment]
You might have to update the example script on the homepage for the `playwright_page_event_handlers`  - when copying it as is there are quite a few errors which is misleading.

That said - I have updated my script using the example as a template however, how would I grab the downloads? It doesn't seem to make any reference to the first function.

**Comment by elacuesta** [comment]
The example in the Readme is a simplified version of the [full script](https://github.com/scrapy-plugins/scrapy-playwright/blob/master/examples/events.py) available in the `examples` directory.

`download` does not work as a `PageCoroutine` because there is no `download` coroutine in the [`Page`](https://playwright.dev/python/docs/api/class-page) class.

I think there is some confusion about what a "download" is, as the sample page that you're working with does not initiate any. In this context, downloads are things that get stored in your filesystem, for instance, files. http://quotes.toscrape.com/scroll only works with requests and responses.

Furthermore, in your last example you're using the `handle_response` method as both a Scrapy request callback and an event handler for the Playwright "response" event. That's the cause of the `AttributeError` you posted, because Scrapy requests do not have a `resource_type` attribute. Also, the code will break for Playwright responses because you're trying to access the `meta` attribute which is exclusive to Scrapy responses. It's better to use two separate methods for processing the two types of responses.

**Comment by lime-n** [comment]
That makes better sense, thank you for the clarification. I'll look into developing two separate methods to collect the different response types. Although, when you have the moment, where would the url parameters get stored if not in the downloads? If the response stores the resource types, surely the url parameters must be stored somewhere also - as we get a response 200 for the resource type. For example, the quotes url should have the payload ```page:1``` stored.

**Comment by lime-n** [comment]
On an additional note, I came across this issue on [playwright_python](https://github.com/microsoft/playwright-python/issues/1064). It may only be possible to grab the url-parameters with Firefox, I'll check and see what will return this. Otherwise, if you have any suggestions in the meantime please let me know!

**Comment by lime-n** [comment]
Issue solved.

I have uploaded a working script implementing the results discussed in such cases that others may want to know how to completely automate with `scrapy playwright`, and limit human intervention on the web-browser.

[script](https://github.com/lime-n/Python-Project/blob/main/Scrapy_playwright-project/infinite_scroll.py)
