### ISSUE TITLE
Add certificate and ip adderss

### ISSUE THREAD

**Issue by NiuBlibing** [scrapy-plugins/scrapy-playwright#66]
There is  `certificate`, `ip_address` and `protocol` field in [Response ](https://docs.scrapy.org/en/latest/topics/request-response.html#response-objects)in scrapy, but this project not set them.I checked the playwright [document](https://playwright.dev/python/docs/api/class-response#response-security-details), it can get the information by `response.security_details()` , `response.server_addr()` . Is possible to add them?

**Comment by elacuesta** [comment]
Good catch. Those were not available when I first started this integration, and I didn't know they were added. Thanks for bringing this up.

**Comment by elacuesta** [comment]
IP address added in #67, security details added in #68.
Protocol is not available as defined for `scrapy.http.response.Response.protocol` (i.e. application protocol name and version), the closest thing I can think of is the `protocol` key in security details which seems to be the TLS version.
