### ISSUE TITLE
PLAYWRIGHT_PROCESS_REQUEST_HEADERS seems to have no effect

### ISSUE THREAD

**Issue by SamGalanakis** [scrapy-plugins/scrapy-playwright#76]
I have set PLAYWRIGHT_PROCESS_REQUEST_HEADERS to both the provided use_playwright_headers and my own custom function but in both cases the headers end up as what I have as DEFAULT_REQUEST_HEADERS. If I remove DEFAULT_REQUEST_HEADERS it sets User-Agent to Scrapy/2.6.1 (+https://scrapy.org). It looks like the function is being ignored. I checked that self.process_request_headers was being set correctly in the handler so that is not the issue. 

Thanks in advance.

**Comment by elacuesta** [comment]
This part of the code is tested [here](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/tests/test_playwright_requests.py#L272-L319). Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior you describe, maybe pointing to https://httpbin.org/headers to get back the headers you send.

**Comment by SamGalanakis** [comment]
Thanks seems the issue was to do with the PLAYWRIGHT_CONTEXTS I had set, it is working now.
