### ISSUE TITLE
Set option to pass the playwright page as an argument to the Request

### ISSUE THREAD

**Issue by lucasnobre212** [scrapy-plugins/scrapy-playwright#8]
It is possible to pass a _Page_ to meta['playwright-page'] to use it instead of creating another one, but `_download_request_with_page()` will issue a `page.goto(url)` and lose our current page with any coroutine we've run in it.
Suggestion: Make it possible to pass the _Page_ object without using `page.goto`, so we can run code between the coroutines. Another benefit is that playwright will follow more closely the `CONCURRENT_REQUESTS` setting.

**Comment by elacuesta** [comment]
I'm not sure I follow, could you elaborate on the suggestion? How would you navigate to the URL without using `Page.goto`?

**Comment by lucasnobre212** [comment]
I mean something like this.  
```
class AwesomeSpiderWithPage(scrapy.Spider):
    name = "page"

    def start_requests(self):
        coroutines = ...
        yield scrapy.Request(
            url="https://example.org",
            meta={"playwright": True, "playwright_include_page": True, playwright_page_coroutines=coroutines},
        )

    async def parse(self, response):
        # Use the page response to get information from the page or to create conditionals coroutines
        if response.xpath(something):
            new_coroutines = ...
        else:
            new_coroutines = ...
        yield scrapy.Request(
            url="https://example.org",
            meta={"playwright": True, "playwright_include_page": True, coroutines=new_coroutines},
        )
```
So we can check if something is happening to the page before continuing the coroutines or if we should change them. This is almost possible right now, because the handler checks if we are passing the page or not before creating a new one.   
https://github.com/scrapy-plugins/scrapy-playwright/blob/ced7eb88f52b1c1e55d6368a2e9223d1855badea/scrapy_playwright/handler.py#L128-L130  

But after this we use a `Page.goto` without checking if we are keeping the page or not  
https://github.com/scrapy-plugins/scrapy-playwright/blob/ced7eb88f52b1c1e55d6368a2e9223d1855badea/scrapy_playwright/handler.py#L156-L160

I am suggesting this because it would be possible to use coroutines in playwright without going out of the Scrapy's request workflow

**Comment by elacuesta** [comment]
If I understand correctly, I think "going out of the Scrapy's request workflow" would actually be better here, because it would be more explicit. It's generally considered an bad pattern to request the same URL again from a callback. Furthermore, without `goto` there would be no playwright response to read headers or status code, needed to create the scrapy response for the second request.
