### ISSUE TITLE
Сookies are lost

### ISSUE THREAD

**Issue by Shleif91** [scrapy-plugins/scrapy-playwright#83]
I've tried experiments with the settings and nothing seems to help. The debug shows that the next request contains only the first cookie from the previous response

```
    def get_meta(self):
        return {
            "dont_merge_cookies": False,
            "cookiejar": 1,
            "playwright": True,
            "playwright_context": "first",
        }

    def start_requests(self):
        yield scrapy.Request(self.link_service.get_next_link(), dont_filter=True,
                             meta=self.get_meta(), errback=self.errback)

    def parse(self, response):
        for item in response.css('div[data-zone-name="snippetList"] > div[data-zone-name="OfferSnippet"]'):
            data = json.loads(item.attrib['data-zone-data'])
            self.offer_repository.add(Offer(
                item.css('a[data-zone-name="offerLink"] > span::text').get(),
                data['price']
            ))
        next_page_path = response.css('a[aria-label="Следующая страница"]')
        if next_page_path:
            yield scrapy.Request(self.BASE_URL + next_page_path.attrib['href'], dont_filter=True,
                                 meta=self.get_meta(), errback=self.errback)
```
Logs:
> 2022-04-26 20:07:31 [scrapy.downloadermiddlewares.cookies] DEBUG: Received cookies from: <200 https://market.yandex.ru/product--planshet-huawei-matepad-11-wi-fi/994759003/offers?cpa=1&grhow=supplier&lr=213&local-offers-first=0>
> **Set-Cookie:** src-wprid=0; Domain=.market.yandex.ru; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
> src-utm-source-service=0; Domain=.market.yandex.ru; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
> src-baobab-event-id=0; Domain=.market.yandex.ru; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
> src-pof=0; Domain=.market.yandex.ru; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
> visits=1650992847-1650992847-1650992847; Domain=.market.yandex.ru; Path=/; Expires=Thu, 31 Dec 2037 21:00:00 GMT; Secure
> lr=213; Domain=.market.yandex.ru; Path=/; Expires=Tue, 26 Apr 2022 19:07:27 GMT
> market_cpa=0; Domain=.market.yandex.ru; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
> parent_reqid_seq=1650992847340%2Fc4137b3a6379b5a86d4431ba91dd0500; Domain=market.yandex.ru; Path=/; Secure
> cmp-merge=true; Domain=.market.yandex.ru; Path=/; Expires=Thu, 31 Dec 2037 21:00:00 GMT
> reviews-merge=true; Domain=.market.yandex.ru; Path=/; Expires=Thu, 31 Dec 2037 21:00:00 GMT
> 
> 2022-04-26 20:07:31 [scrapy.core.engine] DEBUG: Crawled (200) <POST https://market.yandex.ru/checkcaptcha?key=00AdDw8yC9GLHOq4SfEMFGVUThrf7Ia4_3%2F1650992839%2F986637f3dd8aacf7c2247381c1f21ada_93687a6a5adf10530c2e1f904bb4bb85&retpath=https%3A%2F%2Fmarket.yandex.ru%2Fproduct%2F994759003%2Foffers%3Fcpa%3D1%26grhow%3Dsupplier%26lr%3D213_166eb4fad8b9b10fcb6adb6254ef7458&u=9394c6a3-9ada42de-c37e2365-fcac24c0&rep=%D0%B3%D0%B8%D0%B3%D0%B0%D0%BD%D1%82%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B8%D0%B7%D1%80%D0%B5%D0%B4%D0%BA%D0%B0> (referer: https://market.yandex.ru/product--planshet-huawei-matepad-11-wi-fi/994759003/offers?cpa=1&grhow=supplier&lr=213&local-offers-first=0) ['playwright']
> 2022-04-26 20:07:31 [scrapy.downloadermiddlewares.cookies] DEBUG: Sending cookies to: <GET https://market.yandex.ru/product--planshet-huawei-matepad-11-wi-fi/994759003/offers?cpa=1&local-offers-first=0&grhow=supplier&page=2>
> **Cookie: src-wprid=0**
> 
> 2022-04-26 20:07:32 [scrapy-playwright] DEBUG: [Context=first] New page created, page count is 1 (1 for all contexts)
> 2022-04-26 20:07:32 [scrapy-playwright] DEBUG: [Context=first] Request: <GET https://market.yandex.ru/product--planshet-huawei-matepad-11-wi-fi/994759003/offers?cpa=1&local-offers-first=0&grhow=supplier&page=2> (resource type: document, referrer: None)

As you can see in the log, only **src-wprid** cookie was sent in the request to the second page

settings.py
```
DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}

TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
PLAYWRIGHT_BROWSER_TYPE = 'firefox'
PLAYWRIGHT_LAUNCH_OPTIONS = {"headless": False}
PLAYWRIGHT_PROCESS_REQUEST_HEADERS = use_playwright_headers
COOKIES_DEBUG = True
```

Scrapy 2.6.1

**Comment by elacuesta** [comment]
A good catch. I'm fairly certain that this is caused by `PLAYWRIGHT_PROCESS_REQUEST_HEADERS=use_playwright_headers`: the `Cookie` header from the Scrapy request (set by Scrapy's `CookiesMiddleware`) is discarded. I don't think there's anything to fix here, this seems reasonable to me, but I hadn't thought about it. I'll add a note in the Readme to avoid further surprises.

**Comment by elacuesta** [comment]
Note added afef146a90c430275d9e99a0969ed65f9239c85f
