### ISSUE TITLE
Got garbled code on some website

### ISSUE THREAD

**Issue by Alienboyplus** [scrapy-plugins/scrapy-playwright#88]
I can get data correctly via using scrapy-playwright in my code on most website like this:
```python
def start_requests(self):
    # my code
    # ......

def parse(self, response):
    page = response.meta["playwright_page"]
    response_text = await page.content()
    with open(self.config.task_name+'.html', 'w', encoding='utf-8') as f:
        f.write(response_text)
    # my code
    # ......
```

But I failed to fetch the right data on another website. (It is actually a rare problem)

I use the code above to save `page.content()`, it shows like this:

![image](https://user-images.githubusercontent.com/38063098/167135816-266f2c3b-b4f7-4007-90bf-b8ca78da48e8.png)

So it is completely not readable.
I don't know how to solve this problem.

Here is my server info:
```
system version: centos 7.6
Scrapy: 2.5.1
scrapy-playwright: 0.0.5
playwright: 1.16.0
...
```

Looking forward to some solutions :)

**Comment by elacuesta** [comment]
Is the body perhaps not encoded using UTF-8 as you're declaring when opening the file?

If you're seeing this output from the Playwright page (given the `await page.content()` call; I'm assuming the `def parse` definition is missing the `async` keyword) instead of the Scrapy response, it's possible that you are facing an upstream issue with Playwright itself. Do you get the same if you run plain `playwright`, without `scrapy-playwright`? i.e.:
```python
import asyncio

from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as p:
        for browser_type in [p.firefox, p.chromium]:
            print("*" * 100)
            browser = await browser_type.launch()
            page = await browser.new_page()
            await page.goto("https://httpbin.org/ip")
            print(await page.content())
            await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by Alienboyplus** [comment]
> Is the body perhaps not encoded using UTF-8 as you're declaring when opening the file?
> 
> If you're seeing this output from the Playwright page (given the `await page.content()` call; I'm assuming the `def parse` definition is missing the `async` keyword) instead of the Scrapy response, it's possible that you are facing an upstream issue with Playwright itself. Do you get the same if you run plain `playwright`, without `scrapy-playwright`? i.e.:
> 
> ```python
> import asyncio
> 
> from playwright.async_api import async_playwright
> 
> 
> async def main():
>     async with async_playwright() as p:
>         for browser_type in [p.firefox, p.chromium]:
>             browser = await browser_type.launch()
>             page = await browser.new_page()
>             await page.goto("https://httpbin.org/ip")
>             print(await page.content())
>             await browser.close()
> 
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```

Thanks for you reply ;)

I added the `async`  before `def main`, but still got the same result.

I am studying how to indentify the coding method of the page's body now.

**Comment by Alienboyplus** [comment]
> Is the body perhaps not encoded using UTF-8 as you're declaring when opening the file?
> 
> If you're seeing this output from the Playwright page (given the `await page.content()` call; I'm assuming the `def parse` definition is missing the `async` keyword) instead of the Scrapy response, it's possible that you are facing an upstream issue with Playwright itself. Do you get the same if you run plain `playwright`, without `scrapy-playwright`? i.e.:
> 
> ```python
> import asyncio
> 
> from playwright.async_api import async_playwright
> 
> 
> async def main():
>     async with async_playwright() as p:
>         for browser_type in [p.firefox, p.chromium]:
>             browser = await browser_type.launch()
>             page = await browser.new_page()
>             await page.goto("https://httpbin.org/ip")
>             print(await page.content())
>             await browser.close()
> 
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```

So I used `document.charset` to check my target page, it is using UTF-8.

I also changed my code like this:
```python
def start_requests(self):
    # my code
    # ......

async def parse(self, response):
    page = response.meta["playwright_page"]
    response_text = await page.content()
    logging.info("response_text")
    with open(self.config.task_name+'.html', 'w', encoding='utf-8') as f:
        f.write(response_text)
    # my code
    # ......
```
Sadly, I still got the same error when I check my log file :(

**Comment by Alienboyplus** [comment]
> 1. I assumed the absence of the `async` keyword in your first example was just a typo, if it wasn't and you actually did not have it before I don't know how the code was running in the first place - using `await` inside a regular function raises `SyntaxError: 'await' outside async function`.
> 2. You're using `scrapy-playwright==0.0.5`, I recommend you to update to a more recent version (latest one is `0.0.15`), as there have been some fixes related to the encoding of response bodies.
> 3. If the problem persists, please report whether or not you get the same results with the [standalone `playwright` script I posted earlier](https://github.com/scrapy-plugins/scrapy-playwright/issues/88#issuecomment-1119972104). If you do, you're having a problem with upstream Playwright and should report it there.

I have just solved this problem, and i did these things:
1. I reinstalled my server system with `centos 7.6`, and then try to use my `.sh` file to set up the environment related to my project.
2. I checked my `.sh` file again and found some useless python packages such as `selenium_wire`. So this time, I didn't `pip install` them.
3. Last year when I try to run my project with scrapy-playwright, an exception showed up and said I need to install some dependencies like `at-spi2-atk`,  `libxkbcommon-x11-devel` and `glibc-2.18`. So I added these to my `.sh` file. This time, I didn't install those dependencies, and it works correctly (`scrapy-playwright==0.0.5` still works)!

So I believe it is just a bug related to the server's environment.
I can get the right data from my target website now.
Thanks !
