### ISSUE TITLE
Using ElementHandle in coroutines?

### ISSUE THREAD

**Issue by fogx** [scrapy-plugins/scrapy-playwright#9]
Is there a way to use [ElementHandle](https://playwright.dev/python/docs/api/class-elementhandle) inside coroutines?
From the doc example:
```
    href_element = await page.query_selector("a")
    await href_element.click()
```

**Comment by elacuesta** [comment]
I think this specific snippet should be equivalent to sending a `scrapy_playwright.page.PageCoroutine` for the "click" coroutine: see the `ClickAndSavePdfSpider` spider in the [examples section](https://github.com/scrapy-plugins/scrapy-playwright#examples).

For the general case, you can always [receive the Page in your callback](https://github.com/scrapy-plugins/scrapy-playwright#receiving-the-page-object-in-the-callback).

**Comment by elacuesta** [comment]
Closing to keep the issue tracker clean, please do not hesitate to reopen if you have further questions.

**Comment by fogx** [comment]
@elacuesta thanks for your reply.
There are some functions that only work with elementHandles. Specifically i am trying to use `scroll_into_view_if_needed`.
I'm guessing the only solution for that would be to use `evaluate`?

**Comment by elacuesta** [comment]
Sounds good, I think. I believe there isn't always a clean translation between the Scrapy and Playwright ways of doing things, in those cases is definitely useful to get the page in the callback and manipulate it directly.
