### ISSUE TITLE
Cannot receive page object in reponse.meta when HTTPCACHE_ENABLED is True

### ISSUE THREAD

**Issue by tomcatmurr** [scrapy-plugins/scrapy-playwright#96]
Getting KeyError: 'playwright_page' in response.meta when scrapy cache is enabled. No network ops like back or goto, just the trivial case.

**Comment by elacuesta** [comment]
It's hard to know without actionable code and logs, but here's my best theoretical explanation.

[`response.meta` is an alias for `response.request.meta`](https://github.com/scrapy/scrapy/blob/2.6.1/scrapy/http/response/__init__.py#L65-L73), i.e. the metadata you see in responses actually belongs to the request object. Scrapy's HTTP cache stores and retrieves responses, not requests. Furthermore, the cache works as a [downloader middleware](https://github.com/scrapy/scrapy/blob/2.6.1/scrapy/downloadermiddlewares/httpcache.py), which means that if there's a response for a processed request, said request won't even reach the scrapy-playwright download handler, so no Playwright Page object will be created.

In any case, AFAIK Playwright pages are heavily tied up to the running context, you probably can't expect a page to be fully functional after being (de)serialized if you're running a new context.

**Comment by goldyard** [comment]
Same problem with me.

**Comment by YngProgrammer** [comment]
Same here, problem was solved by switching the "HTTPCACHE_ENABLED" to False.
It made more sense when @elacuesta explained how the cache worked. Thanks!

**Comment by ethanb1996** [comment]
Have the same problem even when i add  "HTTPCACHE_ENABLED" to False.

Any help will be great :)

**Comment by elacuesta** [comment]
This issue is closed, please provide a [Minimal, Reproducible Example ](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the problem.
